In [16]:
import sys
print(sys.executable)

c:\Users\Dell\cart2Insights\.venv\Scripts\python.exe

In [17]:
import sys
print(sys.executable)

c:\Users\Dell\cart2Insights\.venv\Scripts\python.exe

In [18]:
import pandas as pd

In [19]:
import pandas as pd

customers = pd.read_csv("../data/raw/olist_customers_dataset.csv")

customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [20]:
import pandas as pd

customers = pd.read_csv("../data/raw/olist_customers_dataset.csv")

customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [21]:
import pandas as pd

customers = pd.read_csv("../data/raw/olist_customers_dataset.csv")

print("Shape:")
print(customers.shape)

print("\nColumns:")
print(customers.columns)

print("\nDataset Information:")
customers.info()

print("\nMissing Values:")
print(customers.isnull().sum())

print("\nFirst 5 Rows:")
display(customers.head())
print("Dataset Information:")
customers.info()

print("\nMissing Values:")
print(customers.isnull().sum())

print("\nDuplicate Rows:")
print(customers.duplicated().sum())

Shape:
(99441, 5)

Columns:
Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='str')

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 11.0 MB

Missing Values:
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

First 5 Rows:

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 11.0 MB

Missing Values:
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

Duplicate Rows:
0

In [22]:
print("Dataset Information:")
customers.info()

print("\nMissing Values:")
print(customers.isnull().sum())

print("\nDuplicate Rows:")
print(customers.duplicated().sum())

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 11.0 MB

Missing Values:
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

Duplicate Rows:

0

In [23]:
print("Unique customer IDs:", customers["customer_id"].nunique())
print("Total rows:", len(customers))

Unique customer IDs: 99441
Total rows: 99441

In [24]:
orders = pd.read_csv("../data/raw/olist_orders_dataset.csv")

order_items = pd.read_csv("../data/raw/olist_order_items_dataset.csv")

products = pd.read_csv("../data/raw/olist_products_dataset.csv")

sellers = pd.read_csv("../data/raw/olist_sellers_dataset.csv")

order_payments = pd.read_csv("../data/raw/olist_order_payments_dataset.csv")

order_reviews = pd.read_csv("../data/raw/olist_order_reviews_dataset.csv")

geolocation = pd.read_csv("../data/raw/olist_geolocation_dataset.csv")

category_translation = pd.read_csv(
    "../data/raw/product_category_name_translation.csv"
)

print("All 9 datasets loaded successfully!")

All 9 datasets loaded successfully!

In [25]:
datasets = {
    "customers": customers,
    "orders": orders,
    "order_items": order_items,
    "products": products,
    "sellers": sellers,
    "order_payments": order_payments,
    "order_reviews": order_reviews,
    "geolocation": geolocation,
    "category_translation": category_translation
}

for name, df in datasets.items():
    print(f"{name}: {df.shape}")

customers: (99441, 5)
orders: (99441, 8)
order_items: (112650, 7)
products: (32951, 9)
sellers: (3095, 4)
order_payments: (103886, 5)
order_reviews: (99224, 7)
geolocation: (1000163, 5)
category_translation: (71, 2)

In [26]:
print("Unique customer IDs:", order_items["order_id"].nunique())
print("Total rows:", len(order_items))
print("not unique")

Unique customer IDs: 98666
Total rows: 112650
not unique

In [27]:
for name, df in datasets.items():
    print("\n")
    print(name.upper())
    print("\n")
    print(df.columns.tolist())

CUSTOMERS


['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']


ORDERS


['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']


ORDER_ITEMS


['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']


PRODUCTS


['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']


SELLERS


['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']


ORDER_PAYMENTS


['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']


ORDER_REVIEWS


['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']


GEOLOCATION


['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']


CATEGORY_TRANSLATION


['product_category_name', 'product_category_name_english']

In [28]:
for name, df in datasets.items():
    print("\n")
    print(name.upper())
    print("\n")

    general_info = pd.DataFrame({
        "Column": df.columns,
        "Data Type": df.dtypes.astype(str).values,
        "Missing Values": df.isnull().sum().values,
    
    })
    print("Shape",df.shape)
    print("Duplicated rows",df.duplicated().sum())
    print(general_info.to_string(index=False))

CUSTOMERS


Shape (99441, 5)
Duplicated rows 0
                  Column Data Type  Missing Values
             customer_id       str               0
      customer_unique_id       str               0
customer_zip_code_prefix     int64               0
           customer_city       str               0
          customer_state       str               0


ORDERS


Shape (99441, 8)
Duplicated rows 0
                       Column Data Type  Missing Values
                     order_id       str               0
                  customer_id       str               0
                 order_status       str               0
     order_purchase_timestamp       str               0
            order_approved_at       str             160
 order_delivered_carrier_date       str            1783
order_delivered_customer_date       str            2965
order_estimated_delivery_date       str               0


ORDER_ITEMS


Shape (112650, 7)
Duplicated rows 0
             Column Data Type  Missing Values
           order_id       str               0
      order_item_id     int64               0
         product_id       str               0
          seller_id       str               0
shipping_limit_date       str               0
              price   float64               0
      freight_value   float64               0


PRODUCTS


Shape (32951, 9)
Duplicated rows 0
                    Column Data Type  Missing Values
                product_id       str               0
     product_category_name       str             610
       product_name_lenght   float64             610
product_description_lenght   float64             610
        product_photos_qty   float64             610
          product_weight_g   float64               2
         product_length_cm   float64               2
         product_height_cm   float64               2
          product_width_cm   float64               2


SELLERS


Shape (3095, 4)
Duplicated rows 0
                Column Data Type  Missing Values
             seller_id       str               0
seller_zip_code_prefix     int64               0
           seller_city       str               0
          seller_state       str               0


ORDER_PAYMENTS


Shape (103886, 5)
Duplicated rows 0
              Column Data Type  Missing Values
            order_id       str               0
  payment_sequential     int64               0
        payment_type       str               0
payment_installments     int64               0
       payment_value   float64               0


ORDER_REVIEWS


Shape (99224, 7)
Duplicated rows 0
                 Column Data Type  Missing Values
              review_id       str               0
               order_id       str               0
           review_score     int64               0
   review_comment_title       str           87656
 review_comment_message       str           58247
   review_creation_date       str               0
review_answer_timestamp       str               0


GEOLOCATION


Shape (1000163, 5)
Duplicated rows 261831
                     Column Data Type  Missing Values
geolocation_zip_code_prefix     int64               0
            geolocation_lat   float64               0
            geolocation_lng   float64               0
           geolocation_city       str               0
          geolocation_state       str               0


CATEGORY_TRANSLATION


Shape (71, 2)
Duplicated rows 0
                       Column Data Type  Missing Values
        product_category_name       str               0
product_category_name_english       str               0

In [29]:
for name, df in datasets.items():

    print("\n")
    print(name.upper())
    print("\n")

    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])

    print("Total missing values:", df.isnull().sum().sum())

    print("Total duplicate rows:", df.duplicated().sum())

CUSTOMERS


Rows: 99441
Columns: 5
Total missing values: 0
Total duplicate rows: 0


ORDERS


Rows: 99441
Columns: 8
Total missing values: 4908
Total duplicate rows: 0


ORDER_ITEMS


Rows: 112650
Columns: 7
Total missing values: 0
Total duplicate rows: 0


PRODUCTS


Rows: 32951
Columns: 9
Total missing values: 2448
Total duplicate rows: 0


SELLERS


Rows: 3095
Columns: 4
Total missing values: 0
Total duplicate rows: 0


ORDER_PAYMENTS


Rows: 103886
Columns: 5
Total missing values: 0
Total duplicate rows: 0


ORDER_REVIEWS


Rows: 99224
Columns: 7
Total missing values: 145903
Total duplicate rows: 0


GEOLOCATION


Rows: 1000163
Columns: 5
Total missing values: 0
Total duplicate rows: 261831


CATEGORY_TRANSLATION


Rows: 71
Columns: 2
Total missing values: 0
Total duplicate rows: 0

In [30]:
for name, df in datasets.items():

    missing = df.isnull().sum()
    missing = missing[missing > 0]
    print("\n")
    print(name.upper())
    print("\n")

    if len(missing) == 0:
        print("No missing values")
    else:
        print(missing)

CUSTOMERS


No missing values


ORDERS


order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
dtype: int64


ORDER_ITEMS


No missing values


PRODUCTS


product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64


SELLERS


No missing values


ORDER_PAYMENTS


No missing values


ORDER_REVIEWS


review_comment_title      87656
review_comment_message    58247
dtype: int64


GEOLOCATION


No missing values


CATEGORY_TRANSLATION


No missing values

In [31]:
import pandas as pd

customers = pd.read_csv("../data/raw/olist_customers_dataset.csv")

orders = pd.read_csv("../data/raw/olist_orders_dataset.csv")

order_items = pd.read_csv("../data/raw/olist_order_items_dataset.csv")

order_payments = pd.read_csv("../data/raw/olist_order_payments_dataset.csv")

order_reviews = pd.read_csv("../data/raw/olist_order_reviews_dataset.csv")

In [32]:
key_columns = {
    "customers": "customer_id",
    "orders": "order_id",
    "products": "product_id",
    "sellers": "seller_id",
    
    
}

for table, key in key_columns.items():

    df = datasets[table]

    total_rows = len(df)
    unique_values = df[key].nunique()
    duplicate_values = df[key].duplicated().sum()

    print("\n" + table.upper())
    print("Primary Key:", key)
    print("Total rows:", total_rows)
    print("Unique values:", unique_values)
    print("Duplicate values:", duplicate_values)

CUSTOMERS
Primary Key: customer_id
Total rows: 99441
Unique values: 99441
Duplicate values: 0

ORDERS
Primary Key: order_id
Total rows: 99441
Unique values: 99441
Duplicate values: 0

PRODUCTS
Primary Key: product_id
Total rows: 32951
Unique values: 32951
Duplicate values: 0

SELLERS
Primary Key: seller_id
Total rows: 3095
Unique values: 3095
Duplicate values: 0

In [33]:
order_items.duplicated(
    subset=["order_id", "order_item_id"]).sum()

np.int64(0)

In [34]:
order_payments.duplicated(
    subset=["order_id", "payment_sequential"]).sum()

np.int64(0)

In [35]:
order_reviews.duplicated(
    subset=["order_id", "review_id"]).sum()

np.int64(0)

In [36]:
for name, df in datasets.items():
    print("\n")
    print(name.upper())
    print("\n")
    print(df.isnull().sum())

CUSTOMERS


customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64


ORDERS


order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64


ORDER_ITEMS


order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64


PRODUCTS


product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64


SELLERS


seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64


ORDER_PAYMENTS


order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64


ORDER_REVIEWS


review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64


GEOLOCATION


geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64


CATEGORY_TRANSLATION


product_category_name            0
product_category_name_english    0
dtype: int64

In [37]:
orders.columns.tolist()

['order_id',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_carrier_date',
 'order_delivered_customer_date',
 'order_estimated_delivery_date']

In [38]:
orders[
    [
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date"
    ]
].dtypes

order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

In [39]:
date_columns_orders = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns_orders:
    orders[col] = pd.to_datetime(orders[col])

orders[date_columns_orders].dtypes

order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [40]:
order_items["shipping_limit_date"] = pd.to_datetime(
    order_items["shipping_limit_date"],
)

order_items["shipping_limit_date"].dtype

dtype('<M8[us]')

In [41]:
review_date_columns = [
    "review_creation_date",
    "review_answer_timestamp"
]
for col in review_date_columns:
    order_reviews[col] = pd.to_datetime(
        order_reviews[col]
    )

order_reviews[review_date_columns].dtypes

review_creation_date       datetime64[us]
review_answer_timestamp    datetime64[us]
dtype: object

In [42]:
orders["order_status"].value_counts(dropna=False)

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [43]:
invalid_delivery_dates = orders[
    orders["order_delivered_customer_date"].notna()
    & (
        orders["order_delivered_customer_date"]
        < orders["order_purchase_timestamp"]
    )
]

print("Invalid delivery dates:", len(invalid_delivery_dates))

Invalid delivery dates: 0

In [44]:
invalid_estimated_dates = orders[
    orders["order_estimated_delivery_date"].notna()
    & (
        orders["order_estimated_delivery_date"]
        < orders["order_purchase_timestamp"]
    )
]

print("Invalid estimated delivery dates:", len(invalid_estimated_dates))

Invalid estimated delivery dates: 0

In [45]:
invalid_approval_dates = orders[
    orders["order_approved_at"].notna()
    & (
        orders["order_approved_at"]
        < orders["order_purchase_timestamp"]
    )
]

print("Invalid approval dates:", len(invalid_approval_dates))

Invalid approval dates: 0

In [46]:
invalid_delivery_approval_dates = orders[
    orders["order_delivered_customer_date"].notna()
    & orders["order_approved_at"].notna()
    & (
        orders["order_delivered_customer_date"]
        < orders["order_approved_at"]
    )
]
print(
    "Invalid delivery vs approval dates:",
    len(invalid_delivery_approval_dates)
)

Invalid delivery vs approval dates: 61

In [47]:
invalid_carrier_approval_dates = orders[
    orders["order_delivered_carrier_date"].notna()
    & orders["order_approved_at"].notna()
    & (
        orders["order_delivered_carrier_date"]
        < orders["order_approved_at"]
    )
]

print(
    "Invalid carrier vs approval dates:",
    len(invalid_carrier_approval_dates)
)

Invalid carrier vs approval dates: 1359

In [48]:
orders['carrier_approval_diff_days'] = (
    orders['order_delivered_carrier_date'] -
    orders['order_approved_at']
).dt.total_seconds() / (24 * 60 * 60)

orders.loc[
    orders['carrier_approval_diff_days'] < 0,
    ['order_id', 'order_approved_at', 'order_delivered_carrier_date',
     'carrier_approval_diff_days']
].head(10)

,order_id,order_approved_at,order_delivered_carrier_date,carrier_approval_diff_days
15,dcb36b511fcac050b97cd5c05de84dc3,2018-06-12 23:31:02,2018-06-11 14:54:00,-1.359051
64,688052146432ef8253587b930b01a06d,2018-04-24 18:25:22,2018-04-23 19:19:14,-0.962593
199,58d4c4747ee059eeeb865b349b41f53a,2018-07-26 23:31:53,2018-07-24 12:57:00,-2.440891
210,412fccb2b44a99b36714bca3fef8ad7b,2018-07-23 12:31:53,2018-07-23 12:24:00,-0.005475
415,56a4ac10a4a8f2ba7693523bb439eede,2018-07-27 23:31:09,2018-07-24 14:03:00,-3.394549
481,32e4fa9bb468884309b58b9348de70c3,2018-07-05 16:33:06,2018-07-05 14:50:00,-0.071597
483,4df92d82d79c3b52c7138679fa9b07fc,2018-07-29 23:30:52,2018-07-26 14:46:00,-3.364491
585,16e38caa92e342c7780f68832f832d4d,2018-05-07 16:52:39,2018-05-07 15:09:00,-0.071979
615,b9afddbdcfadc9a87b41a83271c3e888,2018-08-16 14:05:13,2018-08-16 13:27:00,-0.026539
817,6051e6d3da9a50b7325cbe9c81025062,2018-07-05 16:31:26,2018-07-04 12:14:00,-1.178773

In [49]:
orders.loc[
    orders['carrier_approval_diff_days'] < 0,
    'carrier_approval_diff_days'
].describe()

count    1359.000000
mean       -1.031333
std         4.804491
min      -171.219005
25%        -1.081528
50%        -0.715324
75%        -0.058976
max        -0.000243
Name: carrier_approval_diff_days, dtype: float64

In [50]:
invalid_carrier = orders[
    orders['carrier_approval_diff_days'] < 0
]
invalid_carrier[
    [
        'order_id',
        'order_approved_at',
        'order_delivered_carrier_date',
        'carrier_approval_diff_days'
    ]
].head(10)

,order_id,order_approved_at,order_delivered_carrier_date,carrier_approval_diff_days
15,dcb36b511fcac050b97cd5c05de84dc3,2018-06-12 23:31:02,2018-06-11 14:54:00,-1.359051
64,688052146432ef8253587b930b01a06d,2018-04-24 18:25:22,2018-04-23 19:19:14,-0.962593
199,58d4c4747ee059eeeb865b349b41f53a,2018-07-26 23:31:53,2018-07-24 12:57:00,-2.440891
210,412fccb2b44a99b36714bca3fef8ad7b,2018-07-23 12:31:53,2018-07-23 12:24:00,-0.005475
415,56a4ac10a4a8f2ba7693523bb439eede,2018-07-27 23:31:09,2018-07-24 14:03:00,-3.394549
481,32e4fa9bb468884309b58b9348de70c3,2018-07-05 16:33:06,2018-07-05 14:50:00,-0.071597
483,4df92d82d79c3b52c7138679fa9b07fc,2018-07-29 23:30:52,2018-07-26 14:46:00,-3.364491
585,16e38caa92e342c7780f68832f832d4d,2018-05-07 16:52:39,2018-05-07 15:09:00,-0.071979
615,b9afddbdcfadc9a87b41a83271c3e888,2018-08-16 14:05:13,2018-08-16 13:27:00,-0.026539
817,6051e6d3da9a50b7325cbe9c81025062,2018-07-05 16:31:26,2018-07-04 12:14:00,-1.178773

In [51]:
invalid_carrier['carrier_approval_diff_days'].describe()

count    1359.000000
mean       -1.031333
std         4.804491
min      -171.219005
25%        -1.081528
50%        -0.715324
75%        -0.058976
max        -0.000243
Name: carrier_approval_diff_days, dtype: float64

In [52]:
invalid_carrier_delivery = orders[
    orders['order_delivered_customer_date'] <
    orders['order_delivered_carrier_date']
]

len(invalid_carrier_delivery)

23

In [53]:
invalid_carrier_delivery[
    [
        'order_id',
        'order_delivered_carrier_date',
        'order_delivered_customer_date'
    ]
]

,order_id,order_delivered_carrier_date,order_delivered_customer_date
6437,a1abeb653a4d4cd1e142ccb8c82cd069,2017-07-28 16:57:58,2017-07-25 19:32:56
9553,383aa8b2724fe452d9ccd9934a8c628b,2017-07-07 17:22:41,2017-07-06 14:27:51
13487,cb1134f9010d242e9515ad1c78ec0c39,2017-07-20 19:22:02,2017-07-19 14:13:28
14474,dceb62e8fa94b46006c9554fed743df0,2017-08-01 18:23:30,2017-07-26 18:09:10
19268,5f9d46795c3126674e52becb3a1a517f,2017-07-20 23:03:42,2017-07-20 18:52:41
21338,8c78d01de3a9009e23d6877a7cc9be20,2016-10-26 11:41:53,2016-10-25 17:51:46
22520,b27af682321527a6349f1761eb3f360c,2017-06-27 14:51:54,2017-06-26 15:45:35
25393,1cc3ae63caffff2d6c3ee3e78e074acf,2017-08-10 18:28:56,2017-08-10 18:05:38
25646,e37f11cae9985ca58f0b56f268720537,2017-08-01 18:17:47,2017-07-31 17:49:56
27470,fa3e37584f4fdb1ded0e0de700dfcb4e,2017-08-09 18:18:43,2017-08-01 21:13:01
34939,c1e2bf2b7dd3309f2f5356c6b63968fa,2017-03-02 17:34:26,2017-02-14 15:15:57
41636,b866af202be0692766081310cd4085e1,2017-02-20 02:32:08,2017-02-15 03:53:46
45302,29941903985f944b0ffc49c479c1547d,2017-06-09 15:07:29,2017-06-02 11:09:16
49933,76458889992169d3135b264dc13aec67,2016-10-26 11:43:06,2016-10-20 18:03:17
50373,0922ee1619de7b995648e5a8407afb91,2017-07-14 12:41:34,2017-07-12 20:49:42
58428,fbffbaaa30f4077e87ec6acdb835b278,2017-08-04 20:04:17,2017-08-03 20:30:00
68312,3ee6694bb99d5a6db0deceffcd099597,2017-07-11 18:15:40,2017-07-11 17:41:26
71227,19feb5627c41ea1b36a8e50a469b3644,2016-10-26 11:42:05,2016-10-20 19:07:54
74967,d5558a097766363b8e76b38c43332e8a,2017-02-15 08:55:26,2017-02-10 07:58:32
76120,771c4f1f521f462e4b95619e648aaeab,2017-03-30 13:14:34,2017-03-28 17:28:32
78556,ea1dcb4757a844d2642547797bd5feb0,2017-07-27 19:21:31,2017-07-25 19:43:10
90373,99ad48402644a3968f2481defdc57947,2017-08-12 00:03:35,2017-08-10 21:22:31
95634,f688669f48063536e082bb32d634cd46,2016-10-21 18:02:40,2016-10-20 20:33:27

In [54]:
invalid_approval_delivery = orders[
    orders['order_delivered_customer_date'] <
    orders['order_approved_at']
]

len(invalid_approval_delivery)

61

In [55]:
orders['delivery_delay_days'] = (
    orders['order_delivered_customer_date'] -
    orders['order_estimated_delivery_date']
).dt.total_seconds() / (24 * 60 * 60)

In [56]:
orders.loc[
    orders['delivery_delay_days'] > 0,
    'delivery_delay_days'
].describe()

count    7827.000000
mean        9.552206
std        13.951700
min         0.002500
25%         1.867193
50%         5.807894
75%        11.822471
max       188.975081
Name: delivery_delay_days, dtype: float64

In [57]:
invalid_estimated_approval = orders[
    orders['order_estimated_delivery_date'] <
    orders['order_approved_at']
]
len(invalid_estimated_approval)

12

In [58]:
orders[
    [
        'order_purchase_timestamp',
        'order_approved_at',
        'order_delivered_carrier_date',
        'order_delivered_customer_date',
        'order_estimated_delivery_date'
    ]
].isna().sum()

order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [59]:
orders[orders['order_delivered_customer_date'].isna()]['order_status'].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [60]:
id_missing_delivery = orders[
    (orders['order_status'] == 'delivered') &
    (orders['order_delivered_customer_date'].isna())
]

id_missing_delivery[
    [
        'order_id',
        'order_status',
        'order_purchase_timestamp',
        'order_approved_at',
        'order_delivered_carrier_date',
        'order_delivered_customer_date',
        'order_estimated_delivery_date'
    ]
]

,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaT,2017-12-18
20618,f5dd62b788049ad9fc0526e3ad11a097,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaT,2018-07-16
43834,2ebdfc4f15f23b91474edf87475f108e,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaT,2018-07-30
79263,e69f75a717d64fc5ecdfae42b2e8e086,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaT,2018-07-30
82868,0d3268bad9b086af767785e3f0fc0133,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaT,2018-07-24
92643,2d858f451373b04fb5c984a1cc2defaf,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaT,NaT,2017-06-23
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaT,2018-06-26
98038,20edc82cf5400ce95e1afacc25798b31,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaT,2018-07-19

In [61]:
orders[orders['order_delivered_carrier_date'].isna()]['order_status'].value_counts()

order_status
unavailable    609
canceled       550
invoiced       314
processing     301
created          5
approved         2
delivered        2
Name: count, dtype: int64

In [62]:
id_missing_delivery = orders[
    (orders['order_status'] == 'delivered') &
    (orders['order_delivered_customer_date'].isna())
]

id_missing_delivery[
    [
        'order_id',
        'order_status',
        'order_purchase_timestamp',
        'order_approved_at',
        'order_delivered_carrier_date',
        'order_delivered_customer_date',
        'order_estimated_delivery_date'
    ]
]

,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaT,2017-12-18
20618,f5dd62b788049ad9fc0526e3ad11a097,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaT,2018-07-16
43834,2ebdfc4f15f23b91474edf87475f108e,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaT,2018-07-30
79263,e69f75a717d64fc5ecdfae42b2e8e086,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaT,2018-07-30
82868,0d3268bad9b086af767785e3f0fc0133,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaT,2018-07-24
92643,2d858f451373b04fb5c984a1cc2defaf,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaT,NaT,2017-06-23
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaT,2018-06-26
98038,20edc82cf5400ce95e1afacc25798b31,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaT,2018-07-19

In [63]:
orders[orders['order_delivered_carrier_date'].isna()]['order_status'].value_counts()

order_status
unavailable    609
canceled       550
invoiced       314
processing     301
created          5
approved         2
delivered        2
Name: count, dtype: int64

In [64]:
missing_carrier_delivered = orders[
    (orders['order_status'] == 'delivered') &
    (orders['order_delivered_carrier_date'].isna())
]

missing_carrier_delivered[
    [
        'order_id',
        'order_status',
        'order_purchase_timestamp',
        'order_approved_at',
        'order_delivered_carrier_date',
        'order_delivered_customer_date',
        'order_estimated_delivery_date'
    ]
]

,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
73222,2aa91108853cecb43c84a5dc5b277475,delivered,2017-09-29 08:52:58,2017-09-29 09:07:16,NaT,2017-11-20 19:44:47,2017-11-14
92643,2d858f451373b04fb5c984a1cc2defaf,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaT,NaT,2017-06-23

In [65]:
orders['missing_carrier_date'] = (
    orders['order_delivered_carrier_date'].isna()
)

In [66]:
orders[orders['order_approved_at'].isna()]['order_status'].value_counts()

order_status
canceled     141
delivered     14
created        5
Name: count, dtype: int64

In [67]:
missing_approval_delivered = orders[
    (orders['order_status'] == 'delivered') &
    (orders['order_approved_at'].isna())
]

missing_approval_delivered[
    [
        'order_id',
        'order_status',
        'order_purchase_timestamp',
        'order_approved_at',
        'order_delivered_carrier_date',
        'order_delivered_customer_date',
        'order_estimated_delivery_date'
    ]
]

,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
5323,e04abd8149ef81b95221e88f6ed9ab6a,delivered,2017-02-18 14:40:00,NaT,2017-02-23 12:04:47,2017-03-01 13:25:33,2017-03-17
16567,8a9adc69528e1001fc68dd0aaebbb54a,delivered,2017-02-18 12:45:31,NaT,2017-02-23 09:01:52,2017-03-02 10:05:06,2017-03-21
19031,7013bcfc1c97fe719a7b5e05e61c12db,delivered,2017-02-18 13:29:47,NaT,2017-02-22 16:25:25,2017-03-01 08:07:38,2017-03-17
22663,5cf925b116421afa85ee25e99b4c34fb,delivered,2017-02-18 16:48:35,NaT,2017-02-22 11:23:10,2017-03-09 07:28:47,2017-03-31
23156,12a95a3c06dbaec84bcfb0e2da5d228a,delivered,2017-02-17 13:05:55,NaT,2017-02-22 11:23:11,2017-03-02 11:09:19,2017-03-20
26800,c1d4211b3dae76144deccd6c74144a88,delivered,2017-01-19 12:48:08,NaT,2017-01-25 14:56:50,2017-01-30 18:16:01,2017-03-01
38290,d69e5d356402adc8cf17e08b5033acfb,delivered,2017-02-19 01:28:47,NaT,2017-02-23 03:11:48,2017-03-02 03:41:58,2017-03-27
39334,d77031d6a3c8a52f019764e68f211c69,delivered,2017-02-18 11:04:19,NaT,2017-02-23 07:23:36,2017-03-02 16:15:23,2017-03-22
48401,7002a78c79c519ac54022d4f8a65e6e8,delivered,2017-01-19 22:26:59,NaT,2017-01-27 11:08:05,2017-02-06 14:22:19,2017-03-16
61743,2eecb0d85f281280f79fa00f9cec1a95,delivered,2017-02-17 17:21:55,NaT,2017-02-22 11:42:51,2017-03-03 12:16:03,2017-03-20
63052,51eb2eebd5d76a24625b31c33dd41449,delivered,2017-02-18 15:52:27,NaT,2017-02-23 03:09:14,2017-03-07 13:57:47,2017-03-29
67697,88083e8f64d95b932164187484d90212,delivered,2017-02-18 22:49:19,NaT,2017-02-22 11:31:06,2017-03-02 12:06:06,2017-03-21
72407,3c0b8706b065f9919d0505d3b3343881,delivered,2017-02-17 15:53:27,NaT,2017-02-22 11:31:30,2017-03-03 11:47:47,2017-03-23
84999,2babbb4b15e6d2dfe95e2de765c97bce,delivered,2017-02-18 17:15:03,NaT,2017-02-22 11:23:11,2017-03-03 18:43:43,2017-03-31

In [68]:
invalid_purchase_approval = orders[
    orders['order_approved_at'] <
    orders['order_purchase_timestamp']
]

len(invalid_purchase_approval)

0

In [69]:
invalid_purchase_delivery = orders[
    orders['order_delivered_customer_date'] <
    orders['order_purchase_timestamp']
]

len(invalid_purchase_delivery)

0

In [70]:
invalid_purchase_carrier = orders[
    orders['order_delivered_carrier_date'] <
    orders['order_purchase_timestamp']
]

len(invalid_purchase_carrier)

166

In [71]:
invalid_purchase_carrier[
    [
        'order_id',
        'order_purchase_timestamp',
        'order_delivered_carrier_date'
    ]
].head(10)

,order_id,order_purchase_timestamp,order_delivered_carrier_date
615,b9afddbdcfadc9a87b41a83271c3e888,2018-08-16 13:50:48,2018-08-16 13:27:00
1111,ad133696906f6a78826daa0911b7daec,2018-06-15 15:41:22,2018-06-15 14:52:00
1329,74e033208dc13a7b8127eb8e73d09b76,2018-05-02 10:48:44,2018-05-02 09:49:00
1372,a6b58794fd2ba533359a76c08df576e3,2018-05-14 15:18:23,2018-05-14 13:46:00
1864,5792e0b1c8c8a2bf53af468c9a422c88,2018-07-26 13:25:14,2018-07-26 12:42:00
2760,c3eb293fd154223498b6551a728203e8,2018-07-19 14:06:04,2018-07-19 13:49:00
3473,b0c2a7d04b165525254254a728c50a4e,2018-06-07 13:28:30,2018-06-07 13:22:00
3661,2033a4586b5bec3229ebc1675a8ae092,2018-06-12 10:10:25,2018-06-12 10:09:00
4114,08adcddad19d3acf37d1fa01cb9ded1e,2018-06-27 11:16:44,2018-06-27 10:57:00
4159,dee6298ce7d1fb2645141ef9972157aa,2018-04-30 14:06:12,2018-04-30 12:59:00

In [72]:
invalid_purchase_carrier = orders[
    orders['order_delivered_carrier_date'] <
    orders['order_purchase_timestamp']
].copy()

invalid_purchase_carrier['difference_minutes'] = (
    invalid_purchase_carrier['order_purchase_timestamp']
    - invalid_purchase_carrier['order_delivered_carrier_date']
).dt.total_seconds() / 60

invalid_purchase_carrier['difference_minutes'].describe()

count       166.000000
mean       1562.368675
std       19135.430706
min           0.400000
25%          14.066667
50%          35.991667
75%          61.050000
max      246545.883333
Name: difference_minutes, dtype: float64

In [73]:
invalid_purchase_carrier.sort_values(
    'difference_minutes',
    ascending=False
)[
    [
        'order_id',
        'order_purchase_timestamp',
        'order_delivered_carrier_date',
        'difference_minutes'
    ]
].head(10)

,order_id,order_purchase_timestamp,order_delivered_carrier_date,difference_minutes
25883,7c48bb55e8e4f7e56d412e9653db37bc,2018-07-16 18:40:53,2018-01-26 13:35:00,246545.883333
83321,4021cd7611d6d9ce5ffcd24817fc374f,2018-08-18 11:49:40,2018-08-14 06:22:00,6087.666667
67844,db090a16182b263b1e896bb26c6f66cf,2018-07-13 16:14:08,2018-07-13 13:59:00,135.133333
65452,9711d975b961355b4b5d636857e48498,2018-06-13 15:23:50,2018-06-13 13:15:00,128.833333
79401,89d32b64af005178b318f76cd60f2c3c,2018-07-06 11:54:40,2018-07-06 09:48:00,126.666667
13969,6192897f85cb2aff6dd1fca56fddb45e,2018-07-18 13:34:22,2018-07-18 11:33:00,121.366667
43657,3ed559dec69ab96d9074fedaf18650eb,2018-06-15 13:20:09,2018-06-15 11:22:00,118.150000
4256,4e157a36ea9cf89bde6fff57a780b525,2018-08-24 14:37:50,2018-08-24 12:43:00,114.833333
74503,119060af27b04f5fae8b2b0e27eef7f9,2018-06-11 14:34:47,2018-06-11 12:45:00,109.783333
21910,e23c9dcc304042fa90d538be679fa68d,2018-06-13 11:41:23,2018-06-13 09:53:00,108.383333

In [74]:
invalid_carrier_customer = orders[
    orders['order_delivered_customer_date'] < orders['order_delivered_carrier_date']
]

print("Invalid carrier vs customer delivery dates:",
      len(invalid_carrier_customer))

Invalid carrier vs customer delivery dates: 23

In [75]:
invalid_carrier_customer[
    [
        'order_id',
        'order_delivered_carrier_date',
        'order_delivered_customer_date',
        'order_estimated_delivery_date'
    ]
].head(10)

,order_id,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
6437,a1abeb653a4d4cd1e142ccb8c82cd069,2017-07-28 16:57:58,2017-07-25 19:32:56,2017-08-14
9553,383aa8b2724fe452d9ccd9934a8c628b,2017-07-07 17:22:41,2017-07-06 14:27:51,2017-07-21
13487,cb1134f9010d242e9515ad1c78ec0c39,2017-07-20 19:22:02,2017-07-19 14:13:28,2017-08-08
14474,dceb62e8fa94b46006c9554fed743df0,2017-08-01 18:23:30,2017-07-26 18:09:10,2017-08-11
19268,5f9d46795c3126674e52becb3a1a517f,2017-07-20 23:03:42,2017-07-20 18:52:41,2017-07-31
21338,8c78d01de3a9009e23d6877a7cc9be20,2016-10-26 11:41:53,2016-10-25 17:51:46,2016-11-30
22520,b27af682321527a6349f1761eb3f360c,2017-06-27 14:51:54,2017-06-26 15:45:35,2017-07-14
25393,1cc3ae63caffff2d6c3ee3e78e074acf,2017-08-10 18:28:56,2017-08-10 18:05:38,2017-08-25
25646,e37f11cae9985ca58f0b56f268720537,2017-08-01 18:17:47,2017-07-31 17:49:56,2017-08-24
27470,fa3e37584f4fdb1ded0e0de700dfcb4e,2017-08-09 18:18:43,2017-08-01 21:13:01,2017-08-18

In [76]:
invalid_estimated_delivery = orders[
    orders['order_delivered_customer_date'] >
    orders['order_estimated_delivery_date']
]

print("Delivered after estimated date:",
      len(invalid_estimated_delivery))

Delivered after estimated date: 7827

In [77]:
invalid_estimated_delivery[
    [
        'order_id',
        'order_delivered_customer_date',
        'order_estimated_delivery_date'
    ]
].head(10)

,order_id,order_delivered_customer_date,order_estimated_delivery_date
20,203096f03d82e0dffbc41ebc2e2bcfb7,2017-10-09 22:23:46,2017-09-28
25,fbf9ac61453ac646ce8ad9783d7d0af6,2018-03-21 22:03:54,2018-03-12
35,8563039e855156e48fccee4d611a3196,2018-03-20 00:59:25,2018-03-20
41,6ea2f835b4556291ffdc53fa0b3b95e8,2017-12-28 18:59:23,2017-12-21
57,66e4624ae69e7dc89bd50222b59f581f,2018-04-03 13:28:46,2018-04-02
58,a685d016c8a26f71a0bb67821070e398,2017-04-06 13:37:16,2017-03-30
97,6a0a8bfbbe700284feb0845d95e0867f,2017-12-28 19:43:00,2017-12-11
102,a5474c0071dd5d1074e12d417078bbd0,2018-08-03 19:28:47,2018-08-02
110,9d531c565e28c3e0d756192f84d8731f,2018-01-23 21:38:52,2017-12-22
115,8fc207e94fa91a7649c5a5dab690272a,2018-01-20 13:42:22,2017-12-19

In [78]:
missing_delivery_for_delivered = orders[
    (orders['order_status'] == 'delivered') &
    (orders['order_delivered_customer_date'].isna())
]

print("Delivered orders missing customer delivery date:",
      len(missing_delivery_for_delivered))

Delivered orders missing customer delivery date: 8

In [79]:
missing_delivery_for_delivered[
    [
        'order_id',
        'order_status',
        'order_purchase_timestamp',
        'order_delivered_customer_date',
        'order_estimated_delivery_date'
    ]
].head(10)

,order_id,order_status,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,delivered,2017-11-28 17:44:07,NaT,2017-12-18
20618,f5dd62b788049ad9fc0526e3ad11a097,delivered,2018-06-20 06:58:43,NaT,2018-07-16
43834,2ebdfc4f15f23b91474edf87475f108e,delivered,2018-07-01 17:05:11,NaT,2018-07-30
79263,e69f75a717d64fc5ecdfae42b2e8e086,delivered,2018-07-01 22:05:55,NaT,2018-07-30
82868,0d3268bad9b086af767785e3f0fc0133,delivered,2018-07-01 21:14:02,NaT,2018-07-24
92643,2d858f451373b04fb5c984a1cc2defaf,delivered,2017-05-25 23:22:43,NaT,2017-06-23
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,delivered,2018-06-08 12:09:39,NaT,2018-06-26
98038,20edc82cf5400ce95e1afacc25798b31,delivered,2018-06-27 16:09:12,NaT,2018-07-19

In [80]:
non_delivered_with_delivery_date = orders[
    (orders['order_status'] != 'delivered') &
    (orders['order_delivered_customer_date'].notna())
]

print("Non-delivered orders with customer delivery date:",
      len(non_delivered_with_delivery_date))

Non-delivered orders with customer delivery date: 6

In [81]:
non_delivered_with_delivery_date[
    [
        'order_id',
        'order_status',
        'order_delivered_customer_date',
        'order_estimated_delivery_date'
    ]
].head(10)

,order_id,order_status,order_delivered_customer_date,order_estimated_delivery_date
2921,1950d777989f6a877539f53795b4c3c3,canceled,2018-03-21 22:03:51,2018-03-09
8791,dabf2b0e35b423f94618bf965fcb7514,canceled,2016-10-16 14:36:59,2016-11-30
58266,770d331c84e5b214bd9dc70a10b829d0,canceled,2016-10-14 15:07:11,2016-11-29
59332,8beb59392e21af5eb9547ae1a9938d06,canceled,2016-10-19 18:47:43,2016-11-30
92636,65d1e226dfaeb8cdc42f665422522d14,canceled,2016-11-08 10:58:34,2016-11-25
94399,2c45c33d2f9cb8ff8b1c86cc28c11c30,canceled,2016-11-09 14:53:50,2016-12-08

In [82]:
orders[orders['order_approved_at'].isna()]['order_status'].value_counts()

order_status
canceled     141
delivered     14
created        5
Name: count, dtype: int64

In [83]:
missing_approval_delivered = orders[
    (orders['order_status'] == 'delivered') &
    (orders['order_approved_at'].isna())
]

missing_approval_delivered[
    [
        'order_id',
        'order_status',
        'order_purchase_timestamp',
        'order_approved_at',
        'order_delivered_carrier_date',
        'order_delivered_customer_date',
        'order_estimated_delivery_date'
    ]
]

,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
5323,e04abd8149ef81b95221e88f6ed9ab6a,delivered,2017-02-18 14:40:00,NaT,2017-02-23 12:04:47,2017-03-01 13:25:33,2017-03-17
16567,8a9adc69528e1001fc68dd0aaebbb54a,delivered,2017-02-18 12:45:31,NaT,2017-02-23 09:01:52,2017-03-02 10:05:06,2017-03-21
19031,7013bcfc1c97fe719a7b5e05e61c12db,delivered,2017-02-18 13:29:47,NaT,2017-02-22 16:25:25,2017-03-01 08:07:38,2017-03-17
22663,5cf925b116421afa85ee25e99b4c34fb,delivered,2017-02-18 16:48:35,NaT,2017-02-22 11:23:10,2017-03-09 07:28:47,2017-03-31
23156,12a95a3c06dbaec84bcfb0e2da5d228a,delivered,2017-02-17 13:05:55,NaT,2017-02-22 11:23:11,2017-03-02 11:09:19,2017-03-20
26800,c1d4211b3dae76144deccd6c74144a88,delivered,2017-01-19 12:48:08,NaT,2017-01-25 14:56:50,2017-01-30 18:16:01,2017-03-01
38290,d69e5d356402adc8cf17e08b5033acfb,delivered,2017-02-19 01:28:47,NaT,2017-02-23 03:11:48,2017-03-02 03:41:58,2017-03-27
39334,d77031d6a3c8a52f019764e68f211c69,delivered,2017-02-18 11:04:19,NaT,2017-02-23 07:23:36,2017-03-02 16:15:23,2017-03-22
48401,7002a78c79c519ac54022d4f8a65e6e8,delivered,2017-01-19 22:26:59,NaT,2017-01-27 11:08:05,2017-02-06 14:22:19,2017-03-16
61743,2eecb0d85f281280f79fa00f9cec1a95,delivered,2017-02-17 17:21:55,NaT,2017-02-22 11:42:51,2017-03-03 12:16:03,2017-03-20
63052,51eb2eebd5d76a24625b31c33dd41449,delivered,2017-02-18 15:52:27,NaT,2017-02-23 03:09:14,2017-03-07 13:57:47,2017-03-29
67697,88083e8f64d95b932164187484d90212,delivered,2017-02-18 22:49:19,NaT,2017-02-22 11:31:06,2017-03-02 12:06:06,2017-03-21
72407,3c0b8706b065f9919d0505d3b3343881,delivered,2017-02-17 15:53:27,NaT,2017-02-22 11:31:30,2017-03-03 11:47:47,2017-03-23
84999,2babbb4b15e6d2dfe95e2de765c97bce,delivered,2017-02-18 17:15:03,NaT,2017-02-22 11:23:11,2017-03-03 18:43:43,2017-03-31

In [84]:
orders[orders['order_delivered_carrier_date'].isna()]['order_status'].value_counts()

order_status
unavailable    609
canceled       550
invoiced       314
processing     301
created          5
approved         2
delivered        2
Name: count, dtype: int64

In [85]:
missing_carrier = orders[
    orders['order_delivered_carrier_date'].isna()
]

missing_carrier[
    [
        'order_id',
        'order_status',
        'order_purchase_timestamp',
        'order_approved_at',
        'order_delivered_carrier_date',
        'order_delivered_customer_date'
    ]
].head(10)

,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date
6,136cce7faa42fdb2cefd53fdc79a6098,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaT,NaT
103,0760a852e4e9d89eb77bf631eaaf1c84,invoiced,2018-08-03 17:44:42,2018-08-07 06:15:14,NaT,NaT
128,15bed8e2fec7fdbadb186b57c46c92f2,processing,2017-09-03 14:22:03,2017-09-03 14:30:09,NaT,NaT
266,8e24261a7e58791d10cb1bf9da94df5c,unavailable,2017-11-16 15:09:28,2017-11-16 15:26:57,NaT,NaT
324,d3c8851a6651eeff2f73b0e011ac45d0,processing,2016-10-05 22:44:13,2016-10-06 15:51:05,NaT,NaT
397,1b9ecfe83cdc259250e1a8aca174f0ad,canceled,2018-08-04 14:29:27,2018-08-07 04:10:26,NaT,NaT
455,38b7efdf33dd5561f4f5d4f6e07b0414,invoiced,2017-08-01 18:17:41,2017-08-01 18:32:30,NaT,NaT
586,c272bcd21c287498b4883c7512019702,unavailable,2018-01-31 11:31:37,2018-01-31 14:23:50,NaT,NaT
687,37553832a3a89c9b2db59701c357ca67,unavailable,2017-08-14 17:38:02,2017-08-17 00:15:18,NaT,NaT
737,d57e15fb07fd180f06ab3926b39edcd2,unavailable,2018-01-08 19:39:03,2018-01-09 07:26:08,NaT,NaT

In [86]:
orders[orders['order_delivered_customer_date'].isna()]['order_status'].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [87]:
missing_customer_delivery = orders[
    orders['order_delivered_customer_date'].isna()
]

missing_customer_delivery[
    [
        'order_id',
        'order_status',
        'order_purchase_timestamp',
        'order_approved_at',
        'order_delivered_carrier_date',
        'order_delivered_customer_date',
        'order_estimated_delivery_date'
    ]
].head(10)

,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
6,136cce7faa42fdb2cefd53fdc79a6098,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaT,NaT,2017-05-09
44,ee64d42b8cf066f35eac1cf57de1aa85,shipped,2018-06-04 16:44:48,2018-06-05 04:31:18,2018-06-05 14:32:00,NaT,2018-06-28
103,0760a852e4e9d89eb77bf631eaaf1c84,invoiced,2018-08-03 17:44:42,2018-08-07 06:15:14,NaT,NaT,2018-08-21
128,15bed8e2fec7fdbadb186b57c46c92f2,processing,2017-09-03 14:22:03,2017-09-03 14:30:09,NaT,NaT,2017-10-03
154,6942b8da583c2f9957e990d028607019,shipped,2018-01-10 11:33:07,2018-01-11 02:32:30,2018-01-11 19:39:23,NaT,2018-02-07
162,36530871a5e80138db53bcfd8a104d90,shipped,2017-05-09 11:48:37,2017-05-11 11:45:14,2017-05-11 13:21:47,NaT,2017-06-08
231,4d630f57194f5aba1a3d12ce23e71cd9,shipped,2017-11-17 19:53:21,2017-11-18 19:50:31,2017-11-22 17:28:34,NaT,2017-12-13
266,8e24261a7e58791d10cb1bf9da94df5c,unavailable,2017-11-16 15:09:28,2017-11-16 15:26:57,NaT,NaT,2017-12-05
299,3b4ad687e7e5190db827e1ae5a8989dd,shipped,2018-06-28 12:52:15,2018-06-28 13:11:09,2018-07-04 15:20:00,NaT,2018-08-03
305,b68d69564a79dea4776afa33d1d2fcab,shipped,2018-02-28 08:57:03,2018-02-28 10:40:35,2018-03-05 16:10:13,NaT,2018-03-23

In [88]:
print("Duplicate order_id values:",
      orders['order_id'].duplicated().sum())

Duplicate order_id values: 0

In [89]:
duplicate_orders = orders[
    orders['order_id'].duplicated(keep=False)
]

duplicate_orders.sort_values('order_id').head(20)

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date, carrier_approval_diff_days, delivery_delay_days, missing_carrier_date]
Index: []

In [90]:
print("Duplicate complete rows:",
      orders.duplicated().sum())

Duplicate complete rows: 0

In [91]:
orders['order_status'].nunique()

8

In [92]:
orders['order_status'].unique()

<ArrowStringArray>
[  'delivered',    'invoiced',     'shipped',  'processing', 'unavailable',
    'canceled',     'created',    'approved']
Length: 8, dtype: str

In [93]:
orders['order_status'].str.strip().ne(orders['order_status']).sum()

np.int64(0)

In [94]:
orders['order_status'].isna().sum()
orders['order_id'].isna().sum()
orders['order_id'].astype(str).str.strip().eq('').sum()
orders['order_id'].astype(str).str.strip().eq('').sum()
orders['order_id'].str.len().value_counts()
orders['order_id'].str.len().unique()
orders['order_purchase_timestamp'].isna().sum()
orders['order_purchase_timestamp'].min(), orders['order_purchase_timestamp'].max()
orders['order_purchase_timestamp'].duplicated().sum()
orders['order_purchase_timestamp'].max()

Timestamp('2018-10-17 17:30:18')

In [95]:
invalid_purchase_approval = orders[
    orders['order_approved_at'] < orders['order_purchase_timestamp']
]

print("Invalid purchase vs approval dates:",
      len(invalid_purchase_approval))

Invalid purchase vs approval dates: 0

In [96]:
invalid_approval_carrier = orders[
    orders['order_delivered_carrier_date'] <
    orders['order_approved_at']
]

print("Invalid approval vs carrier dates:",
      len(invalid_approval_carrier))

Invalid approval vs carrier dates: 1359

In [97]:
invalid_approval_carrier[
    [
        'order_id',
        'order_status',
        'order_purchase_timestamp',
        'order_approved_at',
        'order_delivered_carrier_date',
        'order_delivered_customer_date',
        'order_estimated_delivery_date'
    ]
].head(10)

,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
15,dcb36b511fcac050b97cd5c05de84dc3,delivered,2018-06-07 19:03:12,2018-06-12 23:31:02,2018-06-11 14:54:00,2018-06-21 15:34:32,2018-07-04
64,688052146432ef8253587b930b01a06d,delivered,2018-04-22 08:48:13,2018-04-24 18:25:22,2018-04-23 19:19:14,2018-04-24 19:31:58,2018-05-15
199,58d4c4747ee059eeeb865b349b41f53a,delivered,2018-07-21 12:49:32,2018-07-26 23:31:53,2018-07-24 12:57:00,2018-07-25 23:58:19,2018-07-31
210,412fccb2b44a99b36714bca3fef8ad7b,delivered,2018-07-22 22:30:05,2018-07-23 12:31:53,2018-07-23 12:24:00,2018-07-24 19:26:42,2018-07-31
415,56a4ac10a4a8f2ba7693523bb439eede,delivered,2018-07-22 13:04:47,2018-07-27 23:31:09,2018-07-24 14:03:00,2018-07-28 00:05:39,2018-08-06
481,32e4fa9bb468884309b58b9348de70c3,delivered,2018-07-04 16:49:21,2018-07-05 16:33:06,2018-07-05 14:50:00,2018-07-07 14:41:18,2018-07-23
483,4df92d82d79c3b52c7138679fa9b07fc,delivered,2018-07-24 11:32:11,2018-07-29 23:30:52,2018-07-26 14:46:00,2018-07-27 18:55:57,2018-08-06
585,16e38caa92e342c7780f68832f832d4d,delivered,2018-05-07 01:09:09,2018-05-07 16:52:39,2018-05-07 15:09:00,2018-05-24 00:31:18,2018-06-07
615,b9afddbdcfadc9a87b41a83271c3e888,delivered,2018-08-16 13:50:48,2018-08-16 14:05:13,2018-08-16 13:27:00,2018-08-24 14:58:37,2018-09-04
817,6051e6d3da9a50b7325cbe9c81025062,delivered,2018-07-03 23:40:16,2018-07-05 16:31:26,2018-07-04 12:14:00,2018-07-05 22:52:28,2018-07-19

In [98]:
invalid_approval_carrier['order_status'].value_counts()

order_status
delivered    1350
shipped         9
Name: count, dtype: int64

In [99]:
invalid_approval_carrier = invalid_approval_carrier.copy()

invalid_approval_carrier['approval_to_carrier_days'] = (
    invalid_approval_carrier['order_delivered_carrier_date']
    - invalid_approval_carrier['order_approved_at']
).dt.total_seconds() / (24 * 60 * 60)

invalid_approval_carrier[
    [
        'order_id',
        'order_status',
        'order_approved_at',
        'order_delivered_carrier_date',
        'approval_to_carrier_days'
    ]
].head(10)

,order_id,order_status,order_approved_at,order_delivered_carrier_date,approval_to_carrier_days
15,dcb36b511fcac050b97cd5c05de84dc3,delivered,2018-06-12 23:31:02,2018-06-11 14:54:00,-1.359051
64,688052146432ef8253587b930b01a06d,delivered,2018-04-24 18:25:22,2018-04-23 19:19:14,-0.962593
199,58d4c4747ee059eeeb865b349b41f53a,delivered,2018-07-26 23:31:53,2018-07-24 12:57:00,-2.440891
210,412fccb2b44a99b36714bca3fef8ad7b,delivered,2018-07-23 12:31:53,2018-07-23 12:24:00,-0.005475
415,56a4ac10a4a8f2ba7693523bb439eede,delivered,2018-07-27 23:31:09,2018-07-24 14:03:00,-3.394549
481,32e4fa9bb468884309b58b9348de70c3,delivered,2018-07-05 16:33:06,2018-07-05 14:50:00,-0.071597
483,4df92d82d79c3b52c7138679fa9b07fc,delivered,2018-07-29 23:30:52,2018-07-26 14:46:00,-3.364491
585,16e38caa92e342c7780f68832f832d4d,delivered,2018-05-07 16:52:39,2018-05-07 15:09:00,-0.071979
615,b9afddbdcfadc9a87b41a83271c3e888,delivered,2018-08-16 14:05:13,2018-08-16 13:27:00,-0.026539
817,6051e6d3da9a50b7325cbe9c81025062,delivered,2018-07-05 16:31:26,2018-07-04 12:14:00,-1.178773

In [100]:
invalid_approval_carrier[
    [
        'order_id',
        'order_status',
        'order_approved_at',
        'order_delivered_carrier_date',
        'order_delivered_customer_date'
    ]
].head(10)

,order_id,order_status,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date
15,dcb36b511fcac050b97cd5c05de84dc3,delivered,2018-06-12 23:31:02,2018-06-11 14:54:00,2018-06-21 15:34:32
64,688052146432ef8253587b930b01a06d,delivered,2018-04-24 18:25:22,2018-04-23 19:19:14,2018-04-24 19:31:58
199,58d4c4747ee059eeeb865b349b41f53a,delivered,2018-07-26 23:31:53,2018-07-24 12:57:00,2018-07-25 23:58:19
210,412fccb2b44a99b36714bca3fef8ad7b,delivered,2018-07-23 12:31:53,2018-07-23 12:24:00,2018-07-24 19:26:42
415,56a4ac10a4a8f2ba7693523bb439eede,delivered,2018-07-27 23:31:09,2018-07-24 14:03:00,2018-07-28 00:05:39
481,32e4fa9bb468884309b58b9348de70c3,delivered,2018-07-05 16:33:06,2018-07-05 14:50:00,2018-07-07 14:41:18
483,4df92d82d79c3b52c7138679fa9b07fc,delivered,2018-07-29 23:30:52,2018-07-26 14:46:00,2018-07-27 18:55:57
585,16e38caa92e342c7780f68832f832d4d,delivered,2018-05-07 16:52:39,2018-05-07 15:09:00,2018-05-24 00:31:18
615,b9afddbdcfadc9a87b41a83271c3e888,delivered,2018-08-16 14:05:13,2018-08-16 13:27:00,2018-08-24 14:58:37
817,6051e6d3da9a50b7325cbe9c81025062,delivered,2018-07-05 16:31:26,2018-07-04 12:14:00,2018-07-05 22:52:28

In [101]:
invalid_approval_carrier[
    [
        'order_approved_at',
        'order_delivered_carrier_date'
    ]
].describe()

                order_approved_at order_delivered_carrier_date
count                        1359                         1359
mean   2018-05-20 00:21:19.643855   2018-05-18 23:36:12.490802
min           2017-03-01 10:51:46          2017-02-22 16:05:29
25%    2018-04-24 18:53:37.500000   2018-04-23 23:12:08.500000
50%           2018-07-05 16:01:00          2018-06-30 08:58:00
75%           2018-07-05 16:32:45          2018-07-05 14:04:00
max           2018-08-27 13:15:03          2018-08-27 10:43:00

In [102]:
invalid_approval_carrier = invalid_approval_carrier.copy()

invalid_approval_carrier['approval_to_carrier_hours'] = (
    invalid_approval_carrier['order_delivered_carrier_date']
    - invalid_approval_carrier['order_approved_at']
).dt.total_seconds() / 3600

invalid_approval_carrier['approval_to_carrier_hours'].describe()

count    1359.000000
mean      -24.751987
std       115.307793
min     -4109.256111
25%       -25.956667
50%       -17.167778
75%        -1.415417
max        -0.005833
Name: approval_to_carrier_hours, dtype: float64

In [103]:
invalid_approval_carrier['order_approved_at'].dt.to_period('M').value_counts().sort_index()

order_approved_at
2017-03      1
2017-04     24
2017-05     14
2017-06      2
2017-07      3
2017-08     21
2017-09     13
2017-12      6
2018-01      1
2018-02     36
2018-03      2
2018-04    393
2018-05     68
2018-06     95
2018-07    565
2018-08    115
Freq: M, Name: count, dtype: int64

In [104]:
invalid_approval_carrier[
    [
        'order_id',
        'order_status',
        'order_approved_at',
        'order_delivered_carrier_date',
        'approval_to_carrier_hours'
    ]
].sort_values('approval_to_carrier_hours').head(10)

,order_id,order_status,order_approved_at,order_delivered_carrier_date,approval_to_carrier_hours
25883,7c48bb55e8e4f7e56d412e9653db37bc,delivered,2018-07-16 18:50:22,2018-01-26 13:35:00,-4109.256111
14562,1fab4ac9d85079b3da72a11475ae1685,delivered,2017-09-13 22:06:11,2017-09-04 13:10:23,-224.930000
46163,0184d4ddb259e1a4cfc2871888cf97b8,delivered,2017-09-13 22:17:15,2017-09-04 14:05:50,-224.190278
98710,1378f9601350615613cc8832d6789c5d,delivered,2017-09-13 22:03:51,2017-09-04 18:07:55,-219.932222
41592,8554cb37f7158cb0b082a841d24a4589,delivered,2017-09-13 21:58:04,2017-09-04 19:12:19,-218.762500
11738,cf72398d0690f841271b695bbfda82d2,delivered,2017-09-13 22:04:39,2017-09-04 20:12:41,-217.866111
85393,40de47dfa620d667117e4a6067b6e1ec,delivered,2017-09-13 21:58:38,2017-09-04 20:36:58,-217.361111
31211,bc4854efd86d9f42140c951c595d20c1,delivered,2017-09-13 22:00:51,2017-09-04 20:49:57,-217.181667
55302,77ca435b03fbf991e5027e3776e37885,delivered,2017-09-13 21:56:08,2017-09-04 20:50:00,-217.102222
68315,580f3268bc2075c5961b2d2929c7a35b,delivered,2017-09-13 22:03:42,2017-09-05 11:58:18,-202.090000

In [105]:
orders[orders['order_delivered_carrier_date'].isna()]['order_status'].value_counts()

order_status
unavailable    609
canceled       550
invoiced       314
processing     301
created          5
approved         2
delivered        2
Name: count, dtype: int64

In [106]:
orders[
    orders['order_delivered_carrier_date'].isna()
].shape[0]

1783

In [107]:
orders[
    orders['order_delivered_carrier_date'].isna()
].shape[0]

1783

In [108]:
orders[
    orders['order_delivered_carrier_date'].isna()
]['order_status'].value_counts()

order_status
unavailable    609
canceled       550
invoiced       314
processing     301
created          5
approved         2
delivered        2
Name: count, dtype: int64

In [109]:
orders[
    (orders['order_status'] == 'delivered') &
    (orders['order_delivered_carrier_date'].isna())
][
    [
        'order_id',
        'order_status',
        'order_purchase_timestamp',
        'order_approved_at',
        'order_delivered_carrier_date',
        'order_delivered_customer_date',
        'order_estimated_delivery_date'
    ]
]

,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
73222,2aa91108853cecb43c84a5dc5b277475,delivered,2017-09-29 08:52:58,2017-09-29 09:07:16,NaT,2017-11-20 19:44:47,2017-11-14
92643,2d858f451373b04fb5c984a1cc2defaf,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaT,NaT,2017-06-23

In [110]:
orders[
    orders['order_delivered_customer_date'].isna()
]['order_status'].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [111]:
orders[
    (orders['order_status'] == 'delivered') &
    (orders['order_delivered_customer_date'].isna())
][
    [
        'order_id',
        'order_status',
        'order_purchase_timestamp',
        'order_approved_at',
        'order_delivered_carrier_date',
        'order_delivered_customer_date',
        'order_estimated_delivery_date'
    ]
]

,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaT,2017-12-18
20618,f5dd62b788049ad9fc0526e3ad11a097,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaT,2018-07-16
43834,2ebdfc4f15f23b91474edf87475f108e,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaT,2018-07-30
79263,e69f75a717d64fc5ecdfae42b2e8e086,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaT,2018-07-30
82868,0d3268bad9b086af767785e3f0fc0133,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaT,2018-07-24
92643,2d858f451373b04fb5c984a1cc2defaf,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaT,NaT,2017-06-23
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaT,2018-06-26
98038,20edc82cf5400ce95e1afacc25798b31,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaT,2018-07-19

In [112]:
invalid_purchase_estimated = orders[
    orders['order_estimated_delivery_date'] <
    orders['order_purchase_timestamp']
]

print("Invalid purchase vs estimated delivery dates:",
      len(invalid_purchase_estimated))

Invalid purchase vs estimated delivery dates: 0

In [113]:
invalid_purchase_estimated = orders[
    orders['order_estimated_delivery_date'] <
    orders['order_purchase_timestamp']
]

print("Invalid purchase vs estimated delivery dates:",
      len(invalid_purchase_estimated))

Invalid purchase vs estimated delivery dates: 0

In [114]:
late_deliveries = orders[
    orders['order_delivered_customer_date'] >
    orders['order_estimated_delivery_date']
]

print("Orders delivered after estimated date:",
      len(late_deliveries))

Orders delivered after estimated date: 7827

In [115]:
late_deliveries = late_deliveries.copy()

late_deliveries['delivery_delay_days'] = (
    late_deliveries['order_delivered_customer_date']
    - late_deliveries['order_estimated_delivery_date']
).dt.total_seconds() / (24 * 60 * 60)

late_deliveries['delivery_delay_days'].describe()

count    7827.000000
mean        9.552206
std        13.951700
min         0.002500
25%         1.867193
50%         5.807894
75%        11.822471
max       188.975081
Name: delivery_delay_days, dtype: float64

In [116]:
orders['order_estimated_delivery_date'].isna().sum()

np.int64(0)

In [117]:
orders['order_estimated_delivery_date'].duplicated().sum()

np.int64(98982)

In [118]:
invalid_estimated_dates = orders[
    orders['order_estimated_delivery_date'] < orders['order_purchase_timestamp']
]

len(invalid_estimated_dates)

0

In [119]:
invalid_carrier_customer = orders[
    orders['order_delivered_customer_date'] <
    orders['order_delivered_carrier_date']
]

len(invalid_carrier_customer)

23

In [120]:
invalid_carrier_customer[
    [
        'order_id',
        'order_status',
        'order_purchase_timestamp',
        'order_approved_at',
        'order_delivered_carrier_date',
        'order_delivered_customer_date',
        'order_estimated_delivery_date'
    ]
]

,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
6437,a1abeb653a4d4cd1e142ccb8c82cd069,delivered,2017-07-20 11:20:52,2017-07-21 06:43:14,2017-07-28 16:57:58,2017-07-25 19:32:56,2017-08-14
9553,383aa8b2724fe452d9ccd9934a8c628b,delivered,2017-07-02 20:58:43,2017-07-02 21:10:20,2017-07-07 17:22:41,2017-07-06 14:27:51,2017-07-21
13487,cb1134f9010d242e9515ad1c78ec0c39,delivered,2017-07-16 12:35:34,2017-07-18 06:03:50,2017-07-20 19:22:02,2017-07-19 14:13:28,2017-08-08
14474,dceb62e8fa94b46006c9554fed743df0,delivered,2017-07-20 20:58:05,2017-07-22 11:45:11,2017-08-01 18:23:30,2017-07-26 18:09:10,2017-08-11
19268,5f9d46795c3126674e52becb3a1a517f,delivered,2017-07-18 11:48:20,2017-07-18 12:03:29,2017-07-20 23:03:42,2017-07-20 18:52:41,2017-07-31
21338,8c78d01de3a9009e23d6877a7cc9be20,delivered,2016-10-08 15:36:50,2016-10-08 18:13:44,2016-10-26 11:41:53,2016-10-25 17:51:46,2016-11-30
22520,b27af682321527a6349f1761eb3f360c,delivered,2017-06-14 20:17:04,2017-06-14 20:30:08,2017-06-27 14:51:54,2017-06-26 15:45:35,2017-07-14
25393,1cc3ae63caffff2d6c3ee3e78e074acf,delivered,2017-08-07 21:35:22,2017-08-08 21:45:15,2017-08-10 18:28:56,2017-08-10 18:05:38,2017-08-25
25646,e37f11cae9985ca58f0b56f268720537,delivered,2017-07-26 11:46:34,2017-07-27 10:10:16,2017-08-01 18:17:47,2017-07-31 17:49:56,2017-08-24
27470,fa3e37584f4fdb1ded0e0de700dfcb4e,delivered,2017-07-30 19:32:23,2017-07-30 19:45:09,2017-08-09 18:18:43,2017-08-01 21:13:01,2017-08-18
34939,c1e2bf2b7dd3309f2f5356c6b63968fa,delivered,2017-02-10 10:19:10,2017-02-10 10:30:13,2017-03-02 17:34:26,2017-02-14 15:15:57,2017-03-15
41636,b866af202be0692766081310cd4085e1,delivered,2017-01-27 14:59:17,2017-01-27 15:30:46,2017-02-20 02:32:08,2017-02-15 03:53:46,2017-04-17
45302,29941903985f944b0ffc49c479c1547d,delivered,2017-05-29 16:16:50,2017-05-29 16:25:16,2017-06-09 15:07:29,2017-06-02 11:09:16,2017-06-23
49933,76458889992169d3135b264dc13aec67,delivered,2016-10-07 10:05:16,2016-10-07 11:24:43,2016-10-26 11:43:06,2016-10-20 18:03:17,2016-11-29
50373,0922ee1619de7b995648e5a8407afb91,delivered,2017-07-11 10:45:44,2017-07-11 10:55:15,2017-07-14 12:41:34,2017-07-12 20:49:42,2017-08-14
58428,fbffbaaa30f4077e87ec6acdb835b278,delivered,2017-07-30 17:58:26,2017-07-31 07:05:07,2017-08-04 20:04:17,2017-08-03 20:30:00,2017-08-18
68312,3ee6694bb99d5a6db0deceffcd099597,delivered,2017-07-07 11:22:13,2017-07-07 12:25:07,2017-07-11 18:15:40,2017-07-11 17:41:26,2017-07-20
71227,19feb5627c41ea1b36a8e50a469b3644,delivered,2016-10-07 17:09:56,2016-10-07 17:32:09,2016-10-26 11:42:05,2016-10-20 19:07:54,2016-12-01
74967,d5558a097766363b8e76b38c43332e8a,delivered,2017-02-04 19:01:33,2017-02-04 19:31:12,2017-02-15 08:55:26,2017-02-10 07:58:32,2017-03-01
76120,771c4f1f521f462e4b95619e648aaeab,delivered,2017-03-22 20:15:15,2017-03-22 20:15:15,2017-03-30 13:14:34,2017-03-28 17:28:32,2017-04-12
78556,ea1dcb4757a844d2642547797bd5feb0,delivered,2017-07-18 13:38:29,2017-07-18 13:50:23,2017-07-27 19:21:31,2017-07-25 19:43:10,2017-08-15
90373,99ad48402644a3968f2481defdc57947,delivered,2017-08-07 16:36:51,2017-08-07 17:20:06,2017-08-12 00:03:35,2017-08-10 21:22:31,2017-09-05
95634,f688669f48063536e082bb32d634cd46,delivered,2016-10-07 10:28:56,2016-10-11 04:56:13,2016-10-21 18:02:40,2016-10-20 20:33:27,2016-11-29

In [121]:
invalid_purchase_customer = orders[
    orders['order_delivered_customer_date'] <
    orders['order_purchase_timestamp']
]

len(invalid_purchase_customer)

0

In [122]:
invalid_approval_customer = orders[
    orders['order_delivered_customer_date'] <
    orders['order_approved_at']
]

len(invalid_approval_customer)

61

In [123]:
orders[
    [
        'order_purchase_timestamp',
        'order_approved_at',
        'order_delivered_carrier_date',
        'order_delivered_customer_date',
        'order_estimated_delivery_date'
    ]
].agg(['min', 'max'])

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
min,2016-09-04 21:15:19,2016-09-15 12:16:38,2016-10-08 10:34:01,2016-10-11 13:46:32,2016-09-30
max,2018-10-17 17:30:18,2018-09-03 17:40:06,2018-09-11 19:48:28,2018-10-17 13:22:46,2018-11-12

In [124]:
orders['order_estimated_delivery_date'].max()
orders.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
carrier_approval_diff_days       1797
delivery_delay_days              2965
missing_carrier_date                0
dtype: int64

In [125]:
import pandas as pd
customers = pd.read_csv("../data/raw/olist_customers_dataset.csv")

In [126]:
customers.info()
customers['customer_id'].duplicated().sum()
customers.isna().sum()
for col in ['customer_id', 'customer_unique_id', 'customer_city', 'customer_state']:
    print(col, (customers[col].str.strip() == '').sum())

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 11.0 MB
customer_id 0
customer_unique_id 0
customer_city 0
customer_state 0

In [127]:
customers['customer_unique_id'].duplicated().sum()
customers[
    (customers['customer_zip_code_prefix'] < 1000) |
    (customers['customer_zip_code_prefix'] > 99999)
].shape[0]

0

In [128]:
customers['customer_state'].unique()
(customers['customer_zip_code_prefix'] < 0).sum()

np.int64(0)

In [129]:
import pandas as pd
products = pd.read_csv("../data/raw/olist_products_dataset.csv")

In [130]:
products.info()
products['product_id'].duplicated().sum()
products.isna().sum()
products[products['product_category_name'].isna()].head(10)
products[products['product_weight_g'].isna()]

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 3.7 MB

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [131]:
for col in [
    'product_name_lenght',
    'product_description_lenght',
    'product_photos_qty',
    'product_weight_g',
    'product_length_cm',
    'product_height_cm',
    'product_width_cm'
]:
    print(col, (products[col] <= 0).sum())

product_name_lenght 0
product_description_lenght 0
product_photos_qty 0
product_weight_g 4
product_length_cm 0
product_height_cm 0
product_width_cm 0

In [132]:
products[products['product_weight_g'] <= 0]
print("Weight = 0:", (products['product_weight_g'] == 0).sum())
print("Weight < 0:", (products['product_weight_g'] < 0).sum())
products[products['product_weight_g'] == 0]
for col in ['product_length_cm', 'product_height_cm', 'product_width_cm']:
    print(col, "=", (products[col] <= 0).sum())

Weight = 0: 4
Weight < 0: 0
product_length_cm = 0
product_height_cm = 0
product_width_cm = 0

In [133]:
print("Unique categories:", products['product_category_name'].nunique())
print("Missing categories:", products['product_category_name'].isna().sum())
products.duplicated().sum()

Unique categories: 73
Missing categories: 610

np.int64(0)

In [134]:
import pandas as pd
sellers = pd.read_csv("../data/raw/olist_sellers_dataset.csv")

In [135]:
sellers.info()
sellers['seller_id'].duplicated().sum()
sellers.isna().sum()
sellers[['seller_id', 'seller_city', 'seller_state']].apply(
    lambda col: col.astype(str).str.strip().eq('').sum()
)

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 230.3 KB

seller_id       0
seller_city     0
seller_state    0
dtype: int64

In [136]:
((sellers['seller_zip_code_prefix'] < 1000) |
 (sellers['seller_zip_code_prefix'] > 99999)).sum()
(sellers['seller_zip_code_prefix'] < 0).sum()

np.int64(0)

In [137]:
sellers.duplicated().sum()

np.int64(0)

In [138]:
sellers['seller_state'].unique()

<ArrowStringArray>
['SP', 'RJ', 'PE', 'PR', 'GO', 'SC', 'BA', 'DF', 'RS', 'MG', 'RN', 'MT', 'CE',
 'PB', 'AC', 'ES', 'RO', 'PI', 'MS', 'SE', 'MA', 'AM', 'PA']
Length: 23, dtype: str

In [139]:
sellers['seller_city'].str.strip().eq('').sum()

np.int64(0)

In [140]:
import pandas as pd
products = pd.read_csv("../data/raw/olist_products_dataset.csv")

In [141]:
(products[['product_length_cm', 'product_height_cm', 'product_width_cm']] <= 0).sum()

product_length_cm    0
product_height_cm    0
product_width_cm     0
dtype: int64

In [142]:
products[products['product_weight_g'] == 0]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
9769,81781c0fed9fe1ad6e8c81fca1e1cb08,cama_mesa_banho,51.0,529.0,1.0,0.0,30.0,25.0,30.0
13683,8038040ee2a71048d4bdbbdc985b69ab,cama_mesa_banho,48.0,528.0,1.0,0.0,30.0,25.0,30.0
14997,36ba42dd187055e1fbe943b2d11430ca,cama_mesa_banho,53.0,528.0,1.0,0.0,30.0,25.0,30.0
32079,e673e90efa65a5409ff4196c038bb5af,cama_mesa_banho,53.0,528.0,1.0,0.0,30.0,25.0,30.0

In [143]:
products[products['product_category_name'].isna()]['product_id'].isna().sum()

np.int64(0)

In [144]:
products[products['product_category_name'].isna()][
    ['product_name_lenght', 'product_description_lenght', 'product_photos_qty']
].isna().sum()

product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
dtype: int64

In [145]:
products[
    products[['product_weight_g',
              'product_length_cm',
              'product_height_cm',
              'product_width_cm']].isna().any(axis=1)
]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [146]:
products['product_category_name'].dropna().str.strip().eq('').sum()

np.int64(0)

In [147]:
import pandas as pd
order_reviews = pd.read_csv("../data/raw/olist_order_reviews_dataset.csv")

In [148]:
order_reviews.info()
order_reviews[order_reviews['review_id'].duplicated(keep=False)].sort_values('review_id')

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 17.8 MB

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
29841,00130cbe1f9d422698c812ed8ded1919,04a28263e085d399c97ae49e0b477efa,1,NaN,"O cartucho ""original HP"" 60XL não é reconhecid...",2018-03-07 00:00:00,2018-03-20 18:08:23
46678,00130cbe1f9d422698c812ed8ded1919,dfcdfc43867d1c1381bfaf62d6b9c195,1,NaN,"O cartucho ""original HP"" 60XL não é reconhecid...",2018-03-07 00:00:00,2018-03-20 18:08:23
63193,0115633a9c298b6a98bcbe4eee75345f,0c9850b2c179c1ef60d2855e2751d1fa,5,NaN,NaN,2017-09-21 00:00:00,2017-09-26 03:27:47
90677,0115633a9c298b6a98bcbe4eee75345f,78a4201f58af3463bdab842eea4bc801,5,NaN,NaN,2017-09-21 00:00:00,2017-09-26 03:27:47
57280,0174caf0ee5964646040cd94e15ac95e,74db91e33b4e1fd865356c89a61abf1f,1,NaN,Produto entregue dentro de embalagem do fornec...,2018-03-07 00:00:00,2018-03-08 03:00:53
...,...,...,...,...,...,...,...
40378,fe5c833752953fed3209646f1f63b53c,d3775e436e60258e62e678a0f68a0f8d,1,NaN,"Comprei dois produtos e ambos, mesmo enviados ...",2018-02-28 00:00:00,2018-02-28 13:57:52
7870,ff2fc9e68f8aabfbe18d710b83aabd30,2da58e0a7dcfa4ce1e00fad9d03ca3b5,2,NaN,NaN,2018-03-17 00:00:00,2018-03-19 11:44:15
82521,ff2fc9e68f8aabfbe18d710b83aabd30,1078d496cc6ab9a8e6f2be77abf5091b,2,NaN,NaN,2018-03-17 00:00:00,2018-03-19 11:44:15
1985,ffb8cff872a625632ac983eb1f88843c,c88b1d1b157a9999ce368f218a407141,3,NaN,NaN,2017-07-22 00:00:00,2017-07-26 13:41:07
73951,ffb8cff872a625632ac983eb1f88843c,c44883fc2529b4aa03ca90e7e09d95b6,3,NaN,NaN,2017-07-22 00:00:00,2017-07-26 13:41:07

In [149]:
order_reviews['review_id'].duplicated(keep=False).sum()

np.int64(1603)

In [150]:
order_reviews['review_score'].value_counts().sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [151]:
(order_reviews['review_creation_date'] >
 order_reviews['review_answer_timestamp']).sum(0)

C:\Users\Dell\AppData\Local\Temp\ipykernel_16044\2856241715.py:2: Pandas4Warning: Starting with pandas version 4.0 all arguments of sum will be keyword-only.
  order_reviews['review_answer_timestamp']).sum(0)

np.int64(0)

In [152]:
order_reviews.duplicated().sum()

np.int64(0)

In [153]:
order_reviews[
    ['review_comment_title', 'review_comment_message']
].apply(lambda col: col.fillna('').str.strip().eq('').sum())

review_comment_title      87658
review_comment_message    58274
dtype: int64

In [154]:
order_reviews['review_id'].value_counts().head(10)

review_id
c444278834184f72b1484dfe47de7f97    3
308316408775d1600dad81bd3184556d    3
2d6ac45f859465b5c185274a1c929637    3
3415c9f764e478409e8e0660ae816dd2    3
4219a80ab469e3fc9901437b73da3f75    3
e44840754f12fad2b8646712121b349a    3
ddc52555ca27b0fe67d5255147682d2d    3
7b606b0d57b078384f0b58eac1d41d78    3
4d0e6dd087008d1f992d25ef6e1f619f    3
08528f70f579f0c830189efc523d2182    3
Name: count, dtype: int64

In [155]:
order_reviews['order_id'].duplicated().sum()

np.int64(551)

In [156]:
order_reviews[['order_id', 'review_id']].duplicated().sum()

np.int64(0)

In [157]:
order_reviews[
    ['review_comment_title', 'review_comment_message']
].apply(lambda col: col.fillna('').str.strip().eq('').sum())

review_comment_title      87658
review_comment_message    58274
dtype: int64

In [158]:
order_reviews['review_id'].value_counts().head(10)

review_id
c444278834184f72b1484dfe47de7f97    3
308316408775d1600dad81bd3184556d    3
2d6ac45f859465b5c185274a1c929637    3
3415c9f764e478409e8e0660ae816dd2    3
4219a80ab469e3fc9901437b73da3f75    3
e44840754f12fad2b8646712121b349a    3
ddc52555ca27b0fe67d5255147682d2d    3
7b606b0d57b078384f0b58eac1d41d78    3
4d0e6dd087008d1f992d25ef6e1f619f    3
08528f70f579f0c830189efc523d2182    3
Name: count, dtype: int64

In [159]:
order_reviews['order_id'].duplicated().sum()

np.int64(551)

In [160]:
order_reviews[['order_id', 'review_id']].duplicated().sum()

np.int64(0)

In [161]:
order_reviews[['review_creation_date', 'review_answer_timestamp']].agg(['min', 'max'])

    review_creation_date review_answer_timestamp
min  2016-10-02 00:00:00     2016-10-07 18:32:28
max  2018-08-31 00:00:00     2018-10-29 12:27:35

In [162]:
order_reviews[
    order_reviews['review_comment_message'].notna()
]['review_comment_message'].str.strip().eq('').sum()

np.int64(27)

In [163]:
order_reviews['review_id'].str.len().value_counts().sort_index()

review_id
32    99224
Name: count, dtype: int64

In [164]:
order_reviews['order_id'].str.len().value_counts().sort_index()

order_id
32    99224
Name: count, dtype: int64

In [165]:
import pandas as pd
orders = pd.read_csv("../data/raw/olist_orders_dataset.csv")

In [166]:
order_reviews['review_creation_date'] = pd.to_datetime(
    order_reviews['review_creation_date']
)

orders['order_purchase_timestamp'] = pd.to_datetime(
    orders['order_purchase_timestamp']
)

In [167]:
review_order_check = order_reviews.merge(
    orders[['order_id', 'order_purchase_timestamp']],
    on='order_id',
    how='left'
)

(review_order_check['review_creation_date'] <
 review_order_check['order_purchase_timestamp'].dt.date).sum()

np.int64(64)

In [168]:
review_order_check[
    review_order_check['review_creation_date'] <
    review_order_check['order_purchase_timestamp'].dt.date
][[
    'review_id',
    'order_id',
    'review_creation_date',
    'order_purchase_timestamp'
]]

,review_id,order_id,review_creation_date,order_purchase_timestamp
5293,3415c9f764e478409e8e0660ae816dd2,4d59cc2a2e7bb6c0a851725f5888a9b5,2018-07-31,2018-09-06 14:50:07
5503,49f695dffa457eaba90d388a5c37e942,e5215415bb6f76fe3b7cb68103a0d1c0,2016-10-09,2016-10-22 08:25:27
8404,08528f70f579f0c830189efc523d2182,7813842ae95e8c497fc0233232ae815a,2018-08-03,2018-08-17 20:06:36
8486,f1f8696d256889c0fe9962a5d32746e0,392ed9afd714e3c74767d0c4d3e3f477,2018-08-26,2018-09-29 09:13:03
10412,da8e936bc2f1b52ec626f8aa41f3df44,0fb9645c128ac84788798f0129496ca7,2018-08-04,2018-08-21 10:15:51
...,...,...,...,...
92235,48198628b2d43ed394089750acc59c3f,b059ee4de278302d550a3035c4cdb740,2018-06-27,2018-10-16 20:16:02
92382,0f54fea9e89c2a9398b2bd56e3880eda,8d4c637f1accf7a88a4555f02741e606,2018-08-26,2018-08-29 16:27:49
92696,32415bbf6e341d5d517080a796f79b5c,bd35b677fd239386e9861d11ae98ab56,2018-08-29,2018-09-17 17:21:16
92768,4548534449b1f572e357211b90724f1b,a2ac6dad85cf8af5b0afb510a240fe8c,2018-08-18,2018-10-03 18:55:29
93677,b73c8138f998a2caee0d972cee815401,1a5d21f44c73693b9930d0ca33a9d0b1,2018-08-03,2018-08-16 17:50:14

In [169]:
order_reviews['order_id'].isin(orders['order_id']).value_counts()

order_id
True    99224
Name: count, dtype: int64

In [170]:
review_status_check = order_reviews.merge(
    orders[['order_id', 'order_status']],
    on='order_id',
    how='left'
)

review_status_check['order_status'].value_counts()

order_status
delivered      96361
shipped         1043
canceled         609
unavailable      597
invoiced         313
processing       296
created            3
approved           2
Name: count, dtype: int64

In [171]:
review_order_check[
    review_order_check['review_creation_date'] <
    review_order_check['order_purchase_timestamp'].dt.date
][[
    'review_id',
    'order_id',
    'review_creation_date',
    'order_purchase_timestamp'
]]

,review_id,order_id,review_creation_date,order_purchase_timestamp
5293,3415c9f764e478409e8e0660ae816dd2,4d59cc2a2e7bb6c0a851725f5888a9b5,2018-07-31,2018-09-06 14:50:07
5503,49f695dffa457eaba90d388a5c37e942,e5215415bb6f76fe3b7cb68103a0d1c0,2016-10-09,2016-10-22 08:25:27
8404,08528f70f579f0c830189efc523d2182,7813842ae95e8c497fc0233232ae815a,2018-08-03,2018-08-17 20:06:36
8486,f1f8696d256889c0fe9962a5d32746e0,392ed9afd714e3c74767d0c4d3e3f477,2018-08-26,2018-09-29 09:13:03
10412,da8e936bc2f1b52ec626f8aa41f3df44,0fb9645c128ac84788798f0129496ca7,2018-08-04,2018-08-21 10:15:51
...,...,...,...,...
92235,48198628b2d43ed394089750acc59c3f,b059ee4de278302d550a3035c4cdb740,2018-06-27,2018-10-16 20:16:02
92382,0f54fea9e89c2a9398b2bd56e3880eda,8d4c637f1accf7a88a4555f02741e606,2018-08-26,2018-08-29 16:27:49
92696,32415bbf6e341d5d517080a796f79b5c,bd35b677fd239386e9861d11ae98ab56,2018-08-29,2018-09-17 17:21:16
92768,4548534449b1f572e357211b90724f1b,a2ac6dad85cf8af5b0afb510a240fe8c,2018-08-18,2018-10-03 18:55:29
93677,b73c8138f998a2caee0d972cee815401,1a5d21f44c73693b9930d0ca33a9d0b1,2018-08-03,2018-08-16 17:50:14

In [172]:
review_status_check = order_reviews.merge(
    orders[['order_id', 'order_status']],
    on='order_id',
    how='left'
)

review_status_check['order_status'].value_counts()

order_status
delivered      96361
shipped         1043
canceled         609
unavailable      597
invoiced         313
processing       296
created            3
approved           2
Name: count, dtype: int64

In [173]:
order_reviews.dtypes

review_id                             str
order_id                              str
review_score                        int64
review_comment_title                  str
review_comment_message                str
review_creation_date       datetime64[us]
review_answer_timestamp               str
dtype: object

In [174]:
import pandas as pd
order_items = pd.read_csv("../data/raw/olist_order_items_dataset.csv")

In [175]:
order_items.info()
order_items[['order_id', 'order_item_id']].duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 18.4 MB

np.int64(0)

In [176]:
order_items.duplicated().sum()

np.int64(0)

In [177]:
order_items.isna().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [178]:
order_items[['price', 'freight_value']].le(0).sum()

price              0
freight_value    383
dtype: int64

In [179]:
(order_items['freight_value'] == 0).sum(), (order_items['freight_value'] < 0).sum()

(np.int64(383), np.int64(0))

In [180]:
(order_items['order_item_id'] <= 0).sum()

np.int64(0)

In [181]:
order_items[['price', 'freight_value']].describe()

               price  freight_value
count  112650.000000  112650.000000
mean      120.653739      19.990320
std       183.633928      15.806405
min         0.850000       0.000000
25%        39.900000      13.080000
50%        74.990000      16.260000
75%       134.900000      21.150000
max      6735.000000     409.680000

In [182]:
order_items['shipping_limit_date'].agg(['min', 'max'])

min    2016-09-19 00:15:34
max    2020-04-09 22:35:08
Name: shipping_limit_date, dtype: str

In [183]:
order_items['product_id'].isin(products['product_id']).value_counts()

product_id
True    112650
Name: count, dtype: int64

In [184]:
order_items['seller_id'].isin(sellers['seller_id']).value_counts()

seller_id
True    112650
Name: count, dtype: int64

In [185]:
order_items['order_id'].isin(orders['order_id']).value_counts()

order_id
True    112650
Name: count, dtype: int64

In [186]:
order_items.groupby('order_id')['order_item_id'].min().value_counts().sort_index()

order_item_id
1    98666
Name: count, dtype: int64

In [187]:
order_items.groupby('order_id')['order_item_id'].agg(
    lambda x: set(range(1, x.max() + 1)) - set(x)
).loc[lambda x: x.str.len() > 0].head(20)

Series([], Name: order_item_id, dtype: object)

In [188]:
order_items['shipping_limit_date'].isna().sum()

np.int64(0)

In [189]:
order_items['shipping_limit_date'].agg(['min', 'max'])

min    2016-09-19 00:15:34
max    2020-04-09 22:35:08
Name: shipping_limit_date, dtype: str

In [190]:
orders['order_purchase_timestamp'] = pd.to_datetime(
    orders['order_purchase_timestamp']
)

In [191]:
orders['order_purchase_timestamp'] = pd.to_datetime(
    orders['order_purchase_timestamp'],
    errors='coerce'
)

In [192]:
orders['order_purchase_timestamp'].dtype

dtype('<M8[us]')

In [193]:
orders['order_purchase_timestamp'].dt.year

0        2017
1        2018
2        2018
3        2017
4        2018
         ...
99436    2017
99437    2018
99438    2017
99439    2018
99440    2018
Name: order_purchase_timestamp, Length: 99441, dtype: int32

In [194]:
import pandas as pd
products = pd.read_csv("../data/raw/olist_products_dataset.csv")

In [195]:
order_items['shipping_limit_date'] = pd.to_datetime(
    order_items['shipping_limit_date'],
    errors='coerce'
)

In [196]:
order_items['shipping_limit_date'].dtype

dtype('<M8[us]')

In [197]:
order_items[
    order_items['shipping_limit_date'] > orders['order_purchase_timestamp'].max()
][[
    'order_id',
    'order_item_id',
    'shipping_limit_date'
]].sort_values('shipping_limit_date').tail(20)

                               order_id  order_item_id shipping_limit_date
68516  9c94a4ea2f7876660fa6f1b59b69c8e6              1 2020-02-03 20:23:22
8643   13bdf405f961a6deec817d817f5c6624              1 2020-02-05 03:30:51
85729  c2bb89b5c1dd978d507284be78a04cb2              1 2020-04-09 22:35:08
85730  c2bb89b5c1dd978d507284be78a04cb2              2 2020-04-09 22:35:08

In [198]:
order_items['price'].describe()

count    112650.000000
mean        120.653739
std         183.633928
min           0.850000
25%          39.900000
50%          74.990000
75%         134.900000
max        6735.000000
Name: price, dtype: float64

In [199]:
import pandas as pd
order_payments = pd.read_csv("../data/raw/olist_order_payments_dataset.csv")

In [200]:
order_payments.isna().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [201]:
order_payments.describe()

       payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000

In [202]:
order_payments['payment_type'].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [203]:
order_payments['payment_installments'].value_counts().sort_index()

payment_installments
0         2
1     52546
2     12413
3     10461
4      7098
5      5239
6      3920
7      1626
8      4268
9       644
10     5328
11       23
12      133
13       16
14       15
15       74
16        5
17        8
18       27
20       17
21        3
22        1
23        1
24       18
Name: count, dtype: int64

In [204]:
(order_payments['payment_value'] <= 0).sum()

np.int64(9)

In [205]:
order_payments.loc[
    order_payments['payment_value'] <= 0,
    ['order_id', 'payment_type', 'payment_installments', 'payment_value']
]

,order_id,payment_type,payment_installments,payment_value
19922,8bcbe01d44d147f901cd3192671144db,voucher,1,0.0
36822,fa65dad1b0e818e3ccc5cb0e39231352,voucher,1,0.0
43744,6ccb433e00daae1283ccc956189c82ae,voucher,1,0.0
51280,4637ca194b6387e2d538dc89b124b0ee,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,not_defined,1,0.0
62674,45ed6e85398a87c253db47c2d9f48216,voucher,1,0.0
77885,fa65dad1b0e818e3ccc5cb0e39231352,voucher,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,not_defined,1,0.0
100766,b23878b3e8eb4d25a158f57d96331b18,voucher,1,0.0

In [206]:
order_payments.loc[
    order_payments['payment_value'] <= 0,
    ['order_id', 'payment_type', 'payment_installments', 'payment_value']
]

,order_id,payment_type,payment_installments,payment_value
19922,8bcbe01d44d147f901cd3192671144db,voucher,1,0.0
36822,fa65dad1b0e818e3ccc5cb0e39231352,voucher,1,0.0
43744,6ccb433e00daae1283ccc956189c82ae,voucher,1,0.0
51280,4637ca194b6387e2d538dc89b124b0ee,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,not_defined,1,0.0
62674,45ed6e85398a87c253db47c2d9f48216,voucher,1,0.0
77885,fa65dad1b0e818e3ccc5cb0e39231352,voucher,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,not_defined,1,0.0
100766,b23878b3e8eb4d25a158f57d96331b18,voucher,1,0.0

In [207]:
import pandas as pd
orders = pd.read_csv("../data/raw/olist_orders_dataset.csv")

In [208]:
order_payments['order_id'].isin(orders['order_id']).value_counts()

order_id
True    103886
Name: count, dtype: int64

In [209]:
(order_payments['payment_installments'] <= 0).sum()

np.int64(2)

In [210]:
order_payments.loc[
    order_payments['payment_installments'] <= 0,
    ['order_id', 'payment_type', 'payment_installments', 'payment_value']
]

,order_id,payment_type,payment_installments,payment_value
46982,744bade1fcf9ff3f31d860ace076d422,credit_card,0,58.69
79014,1a57108394169c0b47d8f876acc9ba2d,credit_card,0,129.94

In [211]:
order_payments['payment_type'].astype(str).str.strip().eq('').sum()

np.int64(0)

In [212]:
order_payments['payment_type'].unique()

<ArrowStringArray>
['credit_card', 'boleto', 'voucher', 'debit_card', 'not_defined']
Length: 5, dtype: str

In [213]:
(order_payments['payment_sequential'] <= 0).sum()

np.int64(0)

In [214]:
order_payments.duplicated(
    subset=['order_id', 'payment_sequential']
).sum()

np.int64(0)

In [215]:
import pandas as pd
geolocation = pd.read_csv("../data/raw/olist_geolocation_dataset.csv")

In [216]:
geolocation.info()
geolocation.isna().sum()

<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 50.1 MB

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [217]:
geolocation.duplicated().sum()

np.int64(261831)

In [218]:
geolocation['geolocation_zip_code_prefix'].duplicated().sum()

np.int64(981148)

In [219]:
((geolocation['geolocation_zip_code_prefix'] < 1000) |
 (geolocation['geolocation_zip_code_prefix'] > 99999)).sum()

np.int64(0)

In [220]:
(geolocation['geolocation_zip_code_prefix'] < 0).sum()

np.int64(0)

In [221]:
((geolocation['geolocation_lat'] < -90) |
 (geolocation['geolocation_lat'] > 90)).sum()

np.int64(0)

In [222]:
((geolocation['geolocation_lng'] < -180) |
 (geolocation['geolocation_lng'] > 180)).sum()

np.int64(0)

In [223]:
geolocation[['geolocation_lat', 'geolocation_lng']].isna().sum()

geolocation_lat    0
geolocation_lng    0
dtype: int64

In [224]:
import pandas as pd
category_translaction = pd.read_csv("../data/raw/product_category_name_translation.csv")

In [225]:
category_translaction.isna().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [226]:
import pandas as pd

category_translation = pd.read_csv("../data/raw/product_category_name_translation.csv")

In [227]:
category_translation.duplicated().sum()

np.int64(0)

In [228]:
category_translation['product_category_name'].duplicated().sum()

np.int64(0)

In [229]:
import pandas as pd
products = pd.read_csv("../data/raw/olist_products_dataset.csv")

In [230]:
[k for k, v in globals().items() if hasattr(v, 'shape')]

['_',
 '__',
 '___',
 'customers',
 'order_reviews',
 '_4',
 'orders',
 'orders_original',
 'customers_original',
 'products',
 'products_original',
 'sellers',
 'geolocation',
 'order_items',
 'order_payments',
 'category_translation',
 'sellers_original',
 'order_reviews_original',
 'order_items_original',
 'order_payments_original',
 'geolocation_original',
 'category_translation_original',
 '_19',
 '_20',
 'df',
 'general_info',
 'missing',
 'duplicate_values',
 '_33',
 '_34',
 '_35',
 '_38',
 '_39',
 '_40',
 '_41',
 '_42',
 'invalid_delivery_dates',
 'invalid_estimated_dates',
 'invalid_approval_dates',
 'invalid_delivery_approval_dates',
 'invalid_carrier_approval_dates',
 '_48',
 '_49',
 'invalid_carrier',
 '_50',
 '_51',
 'invalid_carrier_delivery',
 '_53',
 'invalid_approval_delivery',
 '_56',
 'invalid_estimated_approval',
 '_58',
 '_59',
 'id_missing_delivery',
 '_60',
 '_61',
 '_62',
 '_63',
 'missing_carrier_delivered',
 '_64',
 '_66',
 'missing_approval_delivered',
 '_67',
 'invalid_purchase_approval',
 'invalid_purchase_delivery',
 'invalid_purchase_carrier',
 '_71',
 '_72',
 '_73',
 'invalid_carrier_customer',
 '_75',
 'invalid_estimated_delivery',
 '_77',
 'missing_delivery_for_delivered',
 '_79',
 'non_delivered_with_delivery_date',
 '_81',
 '_82',
 '_83',
 '_84',
 'missing_carrier',
 '_85',
 '_86',
 'missing_customer_delivery',
 '_87',
 'duplicate_orders',
 '_89',
 '_92',
 '_93',
 'invalid_approval_carrier',
 '_97',
 '_98',
 '_99',
 '_100',
 '_101',
 '_102',
 '_103',
 '_104',
 '_105',
 '_108',
 '_109',
 '_110',
 '_111',
 'invalid_purchase_estimated',
 'late_deliveries',
 '_115',
 '_116',
 '_117',
 '_120',
 'invalid_purchase_customer',
 'invalid_approval_customer',
 '_123',
 '_124',
 '_128',
 '_130',
 '_133',
 '_135',
 '_136',
 '_137',
 '_138',
 '_139',
 '_141',
 '_142',
 '_143',
 '_144',
 '_145',
 '_146',
 '_148',
 '_149',
 '_150',
 '_151',
 '_152',
 '_153',
 '_154',
 '_155',
 '_156',
 '_157',
 '_158',
 '_159',
 '_160',
 '_161',
 '_162',
 '_163',
 '_164',
 'review_order_check',
 '_167',
 '_168',
 '_169',
 'review_status_check',
 '_170',
 '_171',
 '_172',
 '_173',
 '_175',
 '_176',
 '_177',
 '_178',
 '_180',
 '_181',
 '_182',
 '_183',
 '_184',
 '_185',
 '_186',
 '_187',
 '_188',
 '_189',
 '_192',
 '_193',
 '_196',
 '_197',
 '_198',
 '_200',
 '_201',
 '_202',
 '_203',
 '_204',
 '_205',
 '_206',
 '_208',
 '_209',
 '_210',
 '_211',
 '_212',
 '_213',
 '_214',
 '_216',
 '_217',
 '_218',
 '_219',
 '_220',
 '_221',
 '_222',
 '_223',
 'category_translaction',
 '_225',
 '_227',
 '_228']

In [231]:
import pandas as pd
orders = pd.read_csv("../data/raw/olist_orders_dataset.csv")
order_items = pd.read_csv("../data/raw/olist_order_items_dataset.csv")
geolocation = pd.read_csv("../data/raw/olist_geolocation_dataset.csv")
order_reviews = pd.read_csv("../data/raw/olist_order_reviews_dataset.csv")

In [232]:
order_items['price'].describe()

count    112650.000000
mean        120.653739
std         183.633928
min           0.850000
25%          39.900000
50%          74.990000
75%         134.900000
max        6735.000000
Name: price, dtype: float64

In [233]:
order_items['freight_value'].describe()

count    112650.000000
mean         19.990320
std          15.806405
min           0.000000
25%          13.080000
50%          16.260000
75%          21.150000
max         409.680000
Name: freight_value, dtype: float64

In [234]:
(order_items['price'] < 0).sum()

np.int64(0)

In [235]:
geolocation['geolocation_zip_code_prefix'].nunique()

19015

In [236]:
geolocation['geolocation_city'].astype(str).str.strip().eq('').sum()

np.int64(0)

In [237]:
geolocation['geolocation_state'].astype(str).str.strip().eq('').sum()

np.int64(0)

In [238]:
geolocation['geolocation_state'].nunique()

27

In [239]:
geolocation['geolocation_city'].nunique()

8011

In [240]:
import pandas as pd
category_translation = pd.read_csv("../data/raw/product_category_name_translation.csv")

In [241]:
category_translation.columns.tolist()

['product_category_name', 'product_category_name_english']

In [242]:
category_translation.iloc[:, 1].duplicated().sum()

np.int64(0)

In [243]:
import pandas as pd
order_reviews = pd.read_csv("../data/raw/olist_order_reviews_dataset.csv")
order_items = pd.read_csv("../data/raw/olist_order_items_dataset.csv")

In [244]:
order_reviews.duplicated(
    subset=['order_id', 'review_id']
).sum()

np.int64(0)

In [245]:
((order_reviews['review_score'] < 1) |
 (order_reviews['review_score'] > 5)).sum()

np.int64(0)

In [246]:
(order_reviews['review_answer_timestamp'] <
 order_reviews['review_creation_date']).sum()

np.int64(0)

In [247]:
import pandas as pd
orders = pd.read_csv("../data/raw/olist_orders_dataset.csv")

In [248]:
order_reviews['order_id'].isin(orders['order_id']).value_counts()

order_id
True    99224
Name: count, dtype: int64

In [249]:
order_items['order_id'].isin(orders['order_id']).value_counts()

order_id
True    112650
Name: count, dtype: int64

In [250]:
import pandas as pd
sellers = pd.read_csv("../data/raw/olist_sellers_dataset.csv")

In [251]:
order_items['seller_id'].isin(sellers['seller_id']).value_counts()

seller_id
True    112650
Name: count, dtype: int64

In [252]:
import pandas as pd
products = pd.read_csv("../data/raw/olist_products_dataset.csv")

In [253]:
order_items['product_id'].isin(products['product_id']).value_counts()

product_id
True    112650
Name: count, dtype: int64

In [254]:
(order_items['price'] <= 0).sum()

np.int64(0)

In [255]:
(order_items['freight_value'] < 0).sum()

np.int64(0)

In [256]:
order_items['shipping_limit_date'].isna().sum()

np.int64(0)

In [257]:
order_items['shipping_limit_date'] = pd.to_datetime(
    order_items['shipping_limit_date']
)

In [258]:
order_items['shipping_limit_date'].nlargest(10)

85729   2020-04-09 22:35:08
85730   2020-04-09 22:35:08
8643    2020-02-05 03:30:51
68516   2020-02-03 20:23:22
26104   2018-09-18 21:10:15
54967   2018-09-14 12:30:56
11891   2018-09-14 02:09:37
39543   2018-09-13 14:55:28
91384   2018-09-12 13:24:27
93959   2018-09-12 03:15:36
Name: shipping_limit_date, dtype: datetime64[us]

In [259]:
import pandas as pd
customers = pd.read_csv("../data/raw/olist_customers_dataset.csv")
order_reviews = pd.read_csv("../data/raw/olist_order_reviews_dataset.csv")
orders = pd.read_csv("../data/raw/olist_orders_dataset.csv")
products = pd.read_csv("../data/raw/olist_products_dataset.csv")
sellers = pd.read_csv("../data/raw/olist_sellers_dataset.csv")
geolocation = pd.read_csv("../data/raw/olist_geolocation_dataset.csv")
order_items = pd.read_csv("../data/raw/olist_order_items_dataset.csv")
order_payments = pd.read_csv("../data/raw/olist_order_payments_dataset.csv")
category_translation = pd.read_csv("../data/raw/product_category_name_translation.csv")

In [260]:
order_reviews[
    order_reviews['review_id'].duplicated(keep=False)
][['review_id', 'order_id', 'review_score']].sort_values('review_id').head(20)

,review_id,order_id,review_score
29841,00130cbe1f9d422698c812ed8ded1919,04a28263e085d399c97ae49e0b477efa,1
46678,00130cbe1f9d422698c812ed8ded1919,dfcdfc43867d1c1381bfaf62d6b9c195,1
63193,0115633a9c298b6a98bcbe4eee75345f,0c9850b2c179c1ef60d2855e2751d1fa,5
90677,0115633a9c298b6a98bcbe4eee75345f,78a4201f58af3463bdab842eea4bc801,5
57280,0174caf0ee5964646040cd94e15ac95e,74db91e33b4e1fd865356c89a61abf1f,1
92876,0174caf0ee5964646040cd94e15ac95e,f93a732712407c02dce5dd5088d0f47b,1
54832,017808d29fd1f942d97e50184dfb4c13,8daaa9e99d60fbba579cc1c3e3bfae01,5
99167,017808d29fd1f942d97e50184dfb4c13,b1461c8882153b5fe68307c46a506e39,5
20621,0254bd905dc677a6078990aad3331a36,5bf226cf882c5bf4247f89a97c86f273,1
96080,0254bd905dc677a6078990aad3331a36,331b367bdd766f3d1cf518777317b5d9,1
89712,0288d42bef3dfe36930740c9588a570f,33d8795f04dd631f3480d7aaf90da3dc,3
94851,0288d42bef3dfe36930740c9588a570f,f889a5a0b44adc29c5465b99395ac3c1,3
47495,02aa7f5f75e964e3c7efa59a1f515281,d8e17d5f7dacf0970d316e7c03e741e8,3
95860,02aa7f5f75e964e3c7efa59a1f515281,db92613c074f00e53066388d48ad7512,3
71165,034528cb00b6bc981847acafbdf2ae0b,e1e8e3bca903de27e9a1c72b5a5795e0,1
81094,034528cb00b6bc981847acafbdf2ae0b,3d3742a96f24a8fe4e2e57628807e476,1
1988,03a6a25db577d0689440933055111897,2acfdc5131ff2cf4433e668454c9784c,5
9013,03a6a25db577d0689440933055111897,3fde8b7313af6b37b84b5c7594d7add0,5
21587,0467560f511c516ddaa54a60edb0c291,0c995611a99f81268d859184a416f1db,5
24901,0467560f511c516ddaa54a60edb0c291,55b2e390d5d80ada31ad1b795ebeb087,5

In [261]:
orders_original = orders.copy()
customers_original = customers.copy()
products_original = products.copy()
sellers_original = sellers.copy()
order_reviews_original = order_reviews.copy()
order_items_original = order_items.copy()
order_payments_original = order_payments.copy()
geolocation_original = geolocation.copy()
category_translation_original = category_translation.copy()